// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/lyrics.proto

package lyricspb

import (
	commonpb "github.com/Dev-Siri/wavelength/server/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrackLyricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackLyricsRequest) Reset() {
	*x = GetTrackLyricsRequest{}
	mi := &file_proto_lyrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackLyricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackLyricsRequest) ProtoMessage() {}

func (x *GetTrackLyricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lyrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackLyricsRequest.ProtoReflect.Descriptor instead.
func (*GetTrackLyricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lyrics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrackLyricsRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetTrackLyricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Lines         []*commonpb.LyricsLine `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackLyricsResponse) Reset() {
	*x = GetTrackLyricsResponse{}
	mi := &file_proto_lyrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackLyricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackLyricsResponse) ProtoMessage() {}

func (x *GetTrackLyricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lyrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackLyricsResponse.ProtoReflect.Descriptor instead.
func (*GetTrackLyricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lyrics_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrackLyricsResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetTrackLyricsResponse) GetLines() []*commonpb.LyricsLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_proto_lyrics_proto protoreflect.FileDescriptor

const file_proto_lyrics_proto_rawDesc = "" +
	"\n" +
	"\x12proto/lyrics.proto\x12\x06lyrics\x1a\x12proto/common.proto\"2\n" +
	"\x15GetTrackLyricsRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"Z\n" +
	"\x16GetTrackLyricsResponse\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12(\n" +
	"\x05lines\x18\x02 \x03(\v2\x12.common.LyricsLineR\x05lines2_\n" +
	"\fLyricService\x12O\n" +
	"\x0eGetTrackLyrics\x12\x1d.lyrics.GetTrackLyricsRequest\x1a\x1e.lyrics.GetTrackLyricsResponseB=Z;github.com/Dev-Siri/wavelength/server/proto/lyrics;lyricspbb\x06proto3"

var (
	file_proto_lyrics_proto_rawDescOnce sync.Once
	file_proto_lyrics_proto_rawDescData []byte
)

func file_proto_lyrics_proto_rawDescGZIP() []byte {
	file_proto_lyrics_proto_rawDescOnce.Do(func() {
		file_proto_lyrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lyrics_proto_rawDesc), len(file_proto_lyrics_proto_rawDesc)))
	})
	return file_proto_lyrics_proto_rawDescData
}

var file_proto_lyrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lyrics_proto_goTypes = []any{
	(*GetTrackLyricsRequest)(nil),  // 0: lyrics.GetTrackLyricsRequest
	(*GetTrackLyricsResponse)(nil), // 1: lyrics.GetTrackLyricsResponse
	(*commonpb.LyricsLine)(nil),    // 2: common.LyricsLine
}
var file_proto_lyrics_proto_depIdxs = []int32{
	2, // 0: lyrics.GetTrackLyricsResponse.lines:type_name -> common.LyricsLine
	0, // 1: lyrics.LyricService.GetTrackLyrics:input_type -> lyrics.GetTrackLyricsRequest
	1, // 2: lyrics.LyricService.GetTrackLyrics:output_type -> lyrics.GetTrackLyricsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lyrics_proto_init() }
func file_proto_lyrics_proto_init() {
	if File_proto_lyrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lyrics_proto_rawDesc), len(file_proto_lyrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lyrics_proto_goTypes,
		DependencyIndexes: file_proto_lyrics_proto_depIdxs,
		MessageInfos:      file_proto_lyrics_proto_msgTypes,
	}.Build()
	File_proto_lyrics_proto = out.File
	file_proto_lyrics_proto_goTypes = nil
	file_proto_lyrics_proto_depIdxs = nil
}
