// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/lyrics.proto

package lyricspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LyricService_GetTrackLyrics_FullMethodName  = "/lyrics.LyricService/GetTrackLyrics"
	LyricService_RomanizeLyrics_FullMethodName  = "/lyrics.LyricService/RomanizeLyrics"
	LyricService_TranslateLyrics_FullMethodName = "/lyrics.LyricService/TranslateLyrics"
)

// LyricServiceClient is the client API for LyricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LyricServiceClient interface {
	GetTrackLyrics(ctx context.Context, in *GetTrackLyricsRequest, opts ...grpc.CallOption) (*GetTrackLyricsResponse, error)
	RomanizeLyrics(ctx context.Context, in *RomanizeLyricsRequest, opts ...grpc.CallOption) (*RomanizeLyricsResponse, error)
	TranslateLyrics(ctx context.Context, in *TranslateLyricsRequest, opts ...grpc.CallOption) (*TranslateLyricsResponse, error)
}

type lyricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLyricServiceClient(cc grpc.ClientConnInterface) LyricServiceClient {
	return &lyricServiceClient{cc}
}

func (c *lyricServiceClient) GetTrackLyrics(ctx context.Context, in *GetTrackLyricsRequest, opts ...grpc.CallOption) (*GetTrackLyricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackLyricsResponse)
	err := c.cc.Invoke(ctx, LyricService_GetTrackLyrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lyricServiceClient) RomanizeLyrics(ctx context.Context, in *RomanizeLyricsRequest, opts ...grpc.CallOption) (*RomanizeLyricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RomanizeLyricsResponse)
	err := c.cc.Invoke(ctx, LyricService_RomanizeLyrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lyricServiceClient) TranslateLyrics(ctx context.Context, in *TranslateLyricsRequest, opts ...grpc.CallOption) (*TranslateLyricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateLyricsResponse)
	err := c.cc.Invoke(ctx, LyricService_TranslateLyrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LyricServiceServer is the server API for LyricService service.
// All implementations must embed UnimplementedLyricServiceServer
// for forward compatibility.
type LyricServiceServer interface {
	GetTrackLyrics(context.Context, *GetTrackLyricsRequest) (*GetTrackLyricsResponse, error)
	RomanizeLyrics(context.Context, *RomanizeLyricsRequest) (*RomanizeLyricsResponse, error)
	TranslateLyrics(context.Context, *TranslateLyricsRequest) (*TranslateLyricsResponse, error)
	mustEmbedUnimplementedLyricServiceServer()
}

// UnimplementedLyricServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLyricServiceServer struct{}

func (UnimplementedLyricServiceServer) GetTrackLyrics(context.Context, *GetTrackLyricsRequest) (*GetTrackLyricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackLyrics not implemented")
}
func (UnimplementedLyricServiceServer) RomanizeLyrics(context.Context, *RomanizeLyricsRequest) (*RomanizeLyricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RomanizeLyrics not implemented")
}
func (UnimplementedLyricServiceServer) TranslateLyrics(context.Context, *TranslateLyricsRequest) (*TranslateLyricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TranslateLyrics not implemented")
}
func (UnimplementedLyricServiceServer) mustEmbedUnimplementedLyricServiceServer() {}
func (UnimplementedLyricServiceServer) testEmbeddedByValue()                      {}

// UnsafeLyricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LyricServiceServer will
// result in compilation errors.
type UnsafeLyricServiceServer interface {
	mustEmbedUnimplementedLyricServiceServer()
}

func RegisterLyricServiceServer(s grpc.ServiceRegistrar, srv LyricServiceServer) {
	// If the following call panics, it indicates UnimplementedLyricServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LyricService_ServiceDesc, srv)
}

func _LyricService_GetTrackLyrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackLyricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LyricServiceServer).GetTrackLyrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LyricService_GetTrackLyrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LyricServiceServer).GetTrackLyrics(ctx, req.(*GetTrackLyricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LyricService_RomanizeLyrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RomanizeLyricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LyricServiceServer).RomanizeLyrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LyricService_RomanizeLyrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LyricServiceServer).RomanizeLyrics(ctx, req.(*RomanizeLyricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LyricService_TranslateLyrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateLyricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LyricServiceServer).TranslateLyrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LyricService_TranslateLyrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LyricServiceServer).TranslateLyrics(ctx, req.(*TranslateLyricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LyricService_ServiceDesc is the grpc.ServiceDesc for LyricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LyricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lyrics.LyricService",
	HandlerType: (*LyricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrackLyrics",
			Handler:    _LyricService_GetTrackLyrics_Handler,
		},
		{
			MethodName: "RomanizeLyrics",
			Handler:    _LyricService_RomanizeLyrics_Handler,
		},
		{
			MethodName: "TranslateLyrics",
			Handler:    _LyricService_TranslateLyrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lyrics.proto",
}
