// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/playlist.proto

package playlistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaylistService_GetPublicPlaylists_FullMethodName       = "/playlist.PlaylistService/GetPublicPlaylists"
	PlaylistService_GetPlaylistTracksLength_FullMethodName  = "/playlist.PlaylistService/GetPlaylistTracksLength"
	PlaylistService_AddRemovePlaylistTrack_FullMethodName   = "/playlist.PlaylistService/AddRemovePlaylistTrack"
	PlaylistService_ChangePlaylistVisibility_FullMethodName = "/playlist.PlaylistService/ChangePlaylistVisibility"
	PlaylistService_RearrangePlaylistTracks_FullMethodName  = "/playlist.PlaylistService/RearrangePlaylistTracks"
	PlaylistService_DeletePlaylist_FullMethodName           = "/playlist.PlaylistService/DeletePlaylist"
	PlaylistService_GetPlaylistTracks_FullMethodName        = "/playlist.PlaylistService/GetPlaylistTracks"
	PlaylistService_GetUserPlaylists_FullMethodName         = "/playlist.PlaylistService/GetUserPlaylists"
	PlaylistService_GetPlaylistById_FullMethodName          = "/playlist.PlaylistService/GetPlaylistById"
	PlaylistService_EditPlaylist_FullMethodName             = "/playlist.PlaylistService/EditPlaylist"
	PlaylistService_CreatePlaylist_FullMethodName           = "/playlist.PlaylistService/CreatePlaylist"
)

// PlaylistServiceClient is the client API for PlaylistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaylistServiceClient interface {
	GetPublicPlaylists(ctx context.Context, in *GetPublicPlaylistsRequest, opts ...grpc.CallOption) (*GetPublicPlaylistsResponse, error)
	GetPlaylistTracksLength(ctx context.Context, in *PlaylistTracksLengthRequest, opts ...grpc.CallOption) (*PlaylistTracksLengthResponse, error)
	AddRemovePlaylistTrack(ctx context.Context, in *AddRemovePlaylistTrackRequest, opts ...grpc.CallOption) (*AddRemovePlaylistTrackResponse, error)
	ChangePlaylistVisibility(ctx context.Context, in *ChangePlaylistVisibilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RearrangePlaylistTracks(ctx context.Context, in *RearrangePlaylistTracksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePlaylist(ctx context.Context, in *DeletePlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPlaylistTracks(ctx context.Context, in *GetPlaylistTracksRequest, opts ...grpc.CallOption) (*GetPlaylistTracksResponse, error)
	GetUserPlaylists(ctx context.Context, in *GetUserPlaylistsRequest, opts ...grpc.CallOption) (*GetUserPlaylistsResponse, error)
	GetPlaylistById(ctx context.Context, in *GetPlaylistByIdRequest, opts ...grpc.CallOption) (*GetPlaylistByIdResponse, error)
	EditPlaylist(ctx context.Context, in *EditPlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type playlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaylistServiceClient(cc grpc.ClientConnInterface) PlaylistServiceClient {
	return &playlistServiceClient{cc}
}

func (c *playlistServiceClient) GetPublicPlaylists(ctx context.Context, in *GetPublicPlaylistsRequest, opts ...grpc.CallOption) (*GetPublicPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicPlaylistsResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetPublicPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) GetPlaylistTracksLength(ctx context.Context, in *PlaylistTracksLengthRequest, opts ...grpc.CallOption) (*PlaylistTracksLengthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaylistTracksLengthResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetPlaylistTracksLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) AddRemovePlaylistTrack(ctx context.Context, in *AddRemovePlaylistTrackRequest, opts ...grpc.CallOption) (*AddRemovePlaylistTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRemovePlaylistTrackResponse)
	err := c.cc.Invoke(ctx, PlaylistService_AddRemovePlaylistTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) ChangePlaylistVisibility(ctx context.Context, in *ChangePlaylistVisibilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlaylistService_ChangePlaylistVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) RearrangePlaylistTracks(ctx context.Context, in *RearrangePlaylistTracksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlaylistService_RearrangePlaylistTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) DeletePlaylist(ctx context.Context, in *DeletePlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlaylistService_DeletePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) GetPlaylistTracks(ctx context.Context, in *GetPlaylistTracksRequest, opts ...grpc.CallOption) (*GetPlaylistTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistTracksResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetPlaylistTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) GetUserPlaylists(ctx context.Context, in *GetUserPlaylistsRequest, opts ...grpc.CallOption) (*GetUserPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPlaylistsResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetUserPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) GetPlaylistById(ctx context.Context, in *GetPlaylistByIdRequest, opts ...grpc.CallOption) (*GetPlaylistByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistByIdResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetPlaylistById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) EditPlaylist(ctx context.Context, in *EditPlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlaylistService_EditPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlaylistService_CreatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaylistServiceServer is the server API for PlaylistService service.
// All implementations must embed UnimplementedPlaylistServiceServer
// for forward compatibility.
type PlaylistServiceServer interface {
	GetPublicPlaylists(context.Context, *GetPublicPlaylistsRequest) (*GetPublicPlaylistsResponse, error)
	GetPlaylistTracksLength(context.Context, *PlaylistTracksLengthRequest) (*PlaylistTracksLengthResponse, error)
	AddRemovePlaylistTrack(context.Context, *AddRemovePlaylistTrackRequest) (*AddRemovePlaylistTrackResponse, error)
	ChangePlaylistVisibility(context.Context, *ChangePlaylistVisibilityRequest) (*emptypb.Empty, error)
	RearrangePlaylistTracks(context.Context, *RearrangePlaylistTracksRequest) (*emptypb.Empty, error)
	DeletePlaylist(context.Context, *DeletePlaylistRequest) (*emptypb.Empty, error)
	GetPlaylistTracks(context.Context, *GetPlaylistTracksRequest) (*GetPlaylistTracksResponse, error)
	GetUserPlaylists(context.Context, *GetUserPlaylistsRequest) (*GetUserPlaylistsResponse, error)
	GetPlaylistById(context.Context, *GetPlaylistByIdRequest) (*GetPlaylistByIdResponse, error)
	EditPlaylist(context.Context, *EditPlaylistRequest) (*emptypb.Empty, error)
	CreatePlaylist(context.Context, *CreatePlaylistRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPlaylistServiceServer()
}

// UnimplementedPlaylistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaylistServiceServer struct{}

func (UnimplementedPlaylistServiceServer) GetPublicPlaylists(context.Context, *GetPublicPlaylistsRequest) (*GetPublicPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicPlaylists not implemented")
}
func (UnimplementedPlaylistServiceServer) GetPlaylistTracksLength(context.Context, *PlaylistTracksLengthRequest) (*PlaylistTracksLengthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylistTracksLength not implemented")
}
func (UnimplementedPlaylistServiceServer) AddRemovePlaylistTrack(context.Context, *AddRemovePlaylistTrackRequest) (*AddRemovePlaylistTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRemovePlaylistTrack not implemented")
}
func (UnimplementedPlaylistServiceServer) ChangePlaylistVisibility(context.Context, *ChangePlaylistVisibilityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePlaylistVisibility not implemented")
}
func (UnimplementedPlaylistServiceServer) RearrangePlaylistTracks(context.Context, *RearrangePlaylistTracksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RearrangePlaylistTracks not implemented")
}
func (UnimplementedPlaylistServiceServer) DeletePlaylist(context.Context, *DeletePlaylistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) GetPlaylistTracks(context.Context, *GetPlaylistTracksRequest) (*GetPlaylistTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylistTracks not implemented")
}
func (UnimplementedPlaylistServiceServer) GetUserPlaylists(context.Context, *GetUserPlaylistsRequest) (*GetUserPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPlaylists not implemented")
}
func (UnimplementedPlaylistServiceServer) GetPlaylistById(context.Context, *GetPlaylistByIdRequest) (*GetPlaylistByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylistById not implemented")
}
func (UnimplementedPlaylistServiceServer) EditPlaylist(context.Context, *EditPlaylistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EditPlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) CreatePlaylist(context.Context, *CreatePlaylistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) mustEmbedUnimplementedPlaylistServiceServer() {}
func (UnimplementedPlaylistServiceServer) testEmbeddedByValue()                         {}

// UnsafePlaylistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaylistServiceServer will
// result in compilation errors.
type UnsafePlaylistServiceServer interface {
	mustEmbedUnimplementedPlaylistServiceServer()
}

func RegisterPlaylistServiceServer(s grpc.ServiceRegistrar, srv PlaylistServiceServer) {
	// If the following call panics, it indicates UnimplementedPlaylistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaylistService_ServiceDesc, srv)
}

func _PlaylistService_GetPublicPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetPublicPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetPublicPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetPublicPlaylists(ctx, req.(*GetPublicPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_GetPlaylistTracksLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistTracksLengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetPlaylistTracksLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetPlaylistTracksLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetPlaylistTracksLength(ctx, req.(*PlaylistTracksLengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_AddRemovePlaylistTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemovePlaylistTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).AddRemovePlaylistTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_AddRemovePlaylistTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).AddRemovePlaylistTrack(ctx, req.(*AddRemovePlaylistTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_ChangePlaylistVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePlaylistVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).ChangePlaylistVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_ChangePlaylistVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).ChangePlaylistVisibility(ctx, req.(*ChangePlaylistVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_RearrangePlaylistTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RearrangePlaylistTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).RearrangePlaylistTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_RearrangePlaylistTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).RearrangePlaylistTracks(ctx, req.(*RearrangePlaylistTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_DeletePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).DeletePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_DeletePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).DeletePlaylist(ctx, req.(*DeletePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_GetPlaylistTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetPlaylistTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetPlaylistTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetPlaylistTracks(ctx, req.(*GetPlaylistTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_GetUserPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetUserPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetUserPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetUserPlaylists(ctx, req.(*GetUserPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_GetPlaylistById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetPlaylistById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetPlaylistById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetPlaylistById(ctx, req.(*GetPlaylistByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_EditPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).EditPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_EditPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).EditPlaylist(ctx, req.(*EditPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_CreatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).CreatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_CreatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).CreatePlaylist(ctx, req.(*CreatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaylistService_ServiceDesc is the grpc.ServiceDesc for PlaylistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaylistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playlist.PlaylistService",
	HandlerType: (*PlaylistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicPlaylists",
			Handler:    _PlaylistService_GetPublicPlaylists_Handler,
		},
		{
			MethodName: "GetPlaylistTracksLength",
			Handler:    _PlaylistService_GetPlaylistTracksLength_Handler,
		},
		{
			MethodName: "AddRemovePlaylistTrack",
			Handler:    _PlaylistService_AddRemovePlaylistTrack_Handler,
		},
		{
			MethodName: "ChangePlaylistVisibility",
			Handler:    _PlaylistService_ChangePlaylistVisibility_Handler,
		},
		{
			MethodName: "RearrangePlaylistTracks",
			Handler:    _PlaylistService_RearrangePlaylistTracks_Handler,
		},
		{
			MethodName: "DeletePlaylist",
			Handler:    _PlaylistService_DeletePlaylist_Handler,
		},
		{
			MethodName: "GetPlaylistTracks",
			Handler:    _PlaylistService_GetPlaylistTracks_Handler,
		},
		{
			MethodName: "GetUserPlaylists",
			Handler:    _PlaylistService_GetUserPlaylists_Handler,
		},
		{
			MethodName: "GetPlaylistById",
			Handler:    _PlaylistService_GetPlaylistById_Handler,
		},
		{
			MethodName: "EditPlaylist",
			Handler:    _PlaylistService_EditPlaylist_Handler,
		},
		{
			MethodName: "CreatePlaylist",
			Handler:    _PlaylistService_CreatePlaylist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/playlist.proto",
}
