// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/playlist.proto

package playlistpb

import (
	commonpb "github.com/Dev-Siri/wavelength/server/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRemovePlaylistTrackResponse_PlaylistTrackToggleType int32

const (
	AddRemovePlaylistTrackResponse_PLAYLIST_TRACK_TOGGLE_TYPE_UNSPECIFIED AddRemovePlaylistTrackResponse_PlaylistTrackToggleType = 0
	AddRemovePlaylistTrackResponse_PLAYLIST_TRACK_TOGGLE_TYPE_REMOVE      AddRemovePlaylistTrackResponse_PlaylistTrackToggleType = 1
	AddRemovePlaylistTrackResponse_PLAYLIST_TRACK_TOGGLE_TYPE_ADD         AddRemovePlaylistTrackResponse_PlaylistTrackToggleType = 2
)

// Enum value maps for AddRemovePlaylistTrackResponse_PlaylistTrackToggleType.
var (
	AddRemovePlaylistTrackResponse_PlaylistTrackToggleType_name = map[int32]string{
		0: "PLAYLIST_TRACK_TOGGLE_TYPE_UNSPECIFIED",
		1: "PLAYLIST_TRACK_TOGGLE_TYPE_REMOVE",
		2: "PLAYLIST_TRACK_TOGGLE_TYPE_ADD",
	}
	AddRemovePlaylistTrackResponse_PlaylistTrackToggleType_value = map[string]int32{
		"PLAYLIST_TRACK_TOGGLE_TYPE_UNSPECIFIED": 0,
		"PLAYLIST_TRACK_TOGGLE_TYPE_REMOVE":      1,
		"PLAYLIST_TRACK_TOGGLE_TYPE_ADD":         2,
	}
)

func (x AddRemovePlaylistTrackResponse_PlaylistTrackToggleType) Enum() *AddRemovePlaylistTrackResponse_PlaylistTrackToggleType {
	p := new(AddRemovePlaylistTrackResponse_PlaylistTrackToggleType)
	*p = x
	return p
}

func (x AddRemovePlaylistTrackResponse_PlaylistTrackToggleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddRemovePlaylistTrackResponse_PlaylistTrackToggleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_playlist_proto_enumTypes[0].Descriptor()
}

func (AddRemovePlaylistTrackResponse_PlaylistTrackToggleType) Type() protoreflect.EnumType {
	return &file_proto_playlist_proto_enumTypes[0]
}

func (x AddRemovePlaylistTrackResponse_PlaylistTrackToggleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddRemovePlaylistTrackResponse_PlaylistTrackToggleType.Descriptor instead.
func (AddRemovePlaylistTrackResponse_PlaylistTrackToggleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{7, 0}
}

// Request/Response messages
type EditPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverImage    string                 `protobuf:"bytes,3,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlaylistRequest) Reset() {
	*x = EditPlaylistRequest{}
	mi := &file_proto_playlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlaylistRequest) ProtoMessage() {}

func (x *EditPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlaylistRequest.ProtoReflect.Descriptor instead.
func (*EditPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{0}
}

func (x *EditPlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *EditPlaylistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditPlaylistRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

type CreatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorEmail   string                 `protobuf:"bytes,1,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistRequest) Reset() {
	*x = CreatePlaylistRequest{}
	mi := &file_proto_playlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRequest) ProtoMessage() {}

func (x *CreatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlaylistRequest) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

type GetUserPlaylistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPlaylistsRequest) Reset() {
	*x = GetUserPlaylistsRequest{}
	mi := &file_proto_playlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPlaylistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlaylistsRequest) ProtoMessage() {}

func (x *GetUserPlaylistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlaylistsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPlaylistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPlaylistsRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetUserPlaylistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*commonpb.Playlist   `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPlaylistsResponse) Reset() {
	*x = GetUserPlaylistsResponse{}
	mi := &file_proto_playlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPlaylistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlaylistsResponse) ProtoMessage() {}

func (x *GetUserPlaylistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlaylistsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPlaylistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPlaylistsResponse) GetPlaylists() []*commonpb.Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

type GetPlaylistByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistByIdRequest) Reset() {
	*x = GetPlaylistByIdRequest{}
	mi := &file_proto_playlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistByIdRequest) ProtoMessage() {}

func (x *GetPlaylistByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlaylistByIdRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

type GetPlaylistByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *commonpb.Playlist     `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistByIdResponse) Reset() {
	*x = GetPlaylistByIdResponse{}
	mi := &file_proto_playlist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistByIdResponse) ProtoMessage() {}

func (x *GetPlaylistByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlaylistByIdResponse) GetPlaylist() *commonpb.Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type AddRemovePlaylistTrackRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Artists       []*commonpb.EmbeddedArtist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Thumbnail     string                     `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Duration      string                     `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	IsExplicit    bool                       `protobuf:"varint,4,opt,name=is_explicit,json=isExplicit,proto3" json:"is_explicit,omitempty"`
	Title         string                     `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	VideoId       string                     `protobuf:"bytes,6,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoType     commonpb.VideoType         `protobuf:"varint,7,opt,name=video_type,json=videoType,proto3,enum=common.VideoType" json:"video_type,omitempty"`
	PlaylistId    string                     `protobuf:"bytes,8,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Album         *commonpb.EmbeddedAlbum    `protobuf:"bytes,9,opt,name=album,proto3,oneof" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRemovePlaylistTrackRequest) Reset() {
	*x = AddRemovePlaylistTrackRequest{}
	mi := &file_proto_playlist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRemovePlaylistTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemovePlaylistTrackRequest) ProtoMessage() {}

func (x *AddRemovePlaylistTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemovePlaylistTrackRequest.ProtoReflect.Descriptor instead.
func (*AddRemovePlaylistTrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{6}
}

func (x *AddRemovePlaylistTrackRequest) GetArtists() []*commonpb.EmbeddedArtist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *AddRemovePlaylistTrackRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *AddRemovePlaylistTrackRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *AddRemovePlaylistTrackRequest) GetIsExplicit() bool {
	if x != nil {
		return x.IsExplicit
	}
	return false
}

func (x *AddRemovePlaylistTrackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddRemovePlaylistTrackRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *AddRemovePlaylistTrackRequest) GetVideoType() commonpb.VideoType {
	if x != nil {
		return x.VideoType
	}
	return commonpb.VideoType(0)
}

func (x *AddRemovePlaylistTrackRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *AddRemovePlaylistTrackRequest) GetAlbum() *commonpb.EmbeddedAlbum {
	if x != nil {
		return x.Album
	}
	return nil
}

type AddRemovePlaylistTrackResponse struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	ToggleType    AddRemovePlaylistTrackResponse_PlaylistTrackToggleType `protobuf:"varint,1,opt,name=toggle_type,json=toggleType,proto3,enum=playlist.AddRemovePlaylistTrackResponse_PlaylistTrackToggleType" json:"toggle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRemovePlaylistTrackResponse) Reset() {
	*x = AddRemovePlaylistTrackResponse{}
	mi := &file_proto_playlist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRemovePlaylistTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemovePlaylistTrackResponse) ProtoMessage() {}

func (x *AddRemovePlaylistTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemovePlaylistTrackResponse.ProtoReflect.Descriptor instead.
func (*AddRemovePlaylistTrackResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{7}
}

func (x *AddRemovePlaylistTrackResponse) GetToggleType() AddRemovePlaylistTrackResponse_PlaylistTrackToggleType {
	if x != nil {
		return x.ToggleType
	}
	return AddRemovePlaylistTrackResponse_PLAYLIST_TRACK_TOGGLE_TYPE_UNSPECIFIED
}

type RearrangePlaylistTracksRequest struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	PlaylistId    string                                                   `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Updates       []*RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RearrangePlaylistTracksRequest) Reset() {
	*x = RearrangePlaylistTracksRequest{}
	mi := &file_proto_playlist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RearrangePlaylistTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RearrangePlaylistTracksRequest) ProtoMessage() {}

func (x *RearrangePlaylistTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RearrangePlaylistTracksRequest.ProtoReflect.Descriptor instead.
func (*RearrangePlaylistTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{8}
}

func (x *RearrangePlaylistTracksRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *RearrangePlaylistTracksRequest) GetUpdates() []*RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetPlaylistTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistTracksRequest) Reset() {
	*x = GetPlaylistTracksRequest{}
	mi := &file_proto_playlist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistTracksRequest) ProtoMessage() {}

func (x *GetPlaylistTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistTracksRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{9}
}

func (x *GetPlaylistTracksRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

type GetPlaylistTracksResponse struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	PlaylistTracks []*commonpb.PlaylistTrack `protobuf:"bytes,1,rep,name=playlist_tracks,json=playlistTracks,proto3" json:"playlist_tracks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPlaylistTracksResponse) Reset() {
	*x = GetPlaylistTracksResponse{}
	mi := &file_proto_playlist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistTracksResponse) ProtoMessage() {}

func (x *GetPlaylistTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistTracksResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlaylistTracksResponse) GetPlaylistTracks() []*commonpb.PlaylistTrack {
	if x != nil {
		return x.PlaylistTracks
	}
	return nil
}

type DeletePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	AuthUserEmail string                 `protobuf:"bytes,2,opt,name=auth_user_email,json=authUserEmail,proto3" json:"auth_user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlaylistRequest) Reset() {
	*x = DeletePlaylistRequest{}
	mi := &file_proto_playlist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaylistRequest) ProtoMessage() {}

func (x *DeletePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaylistRequest.ProtoReflect.Descriptor instead.
func (*DeletePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *DeletePlaylistRequest) GetAuthUserEmail() string {
	if x != nil {
		return x.AuthUserEmail
	}
	return ""
}

type ChangePlaylistVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	AuthUserEmail string                 `protobuf:"bytes,2,opt,name=auth_user_email,json=authUserEmail,proto3" json:"auth_user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePlaylistVisibilityRequest) Reset() {
	*x = ChangePlaylistVisibilityRequest{}
	mi := &file_proto_playlist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePlaylistVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePlaylistVisibilityRequest) ProtoMessage() {}

func (x *ChangePlaylistVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePlaylistVisibilityRequest.ProtoReflect.Descriptor instead.
func (*ChangePlaylistVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{12}
}

func (x *ChangePlaylistVisibilityRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *ChangePlaylistVisibilityRequest) GetAuthUserEmail() string {
	if x != nil {
		return x.AuthUserEmail
	}
	return ""
}

type PlaylistTracksLengthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistTracksLengthRequest) Reset() {
	*x = PlaylistTracksLengthRequest{}
	mi := &file_proto_playlist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistTracksLengthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistTracksLengthRequest) ProtoMessage() {}

func (x *PlaylistTracksLengthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistTracksLengthRequest.ProtoReflect.Descriptor instead.
func (*PlaylistTracksLengthRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{13}
}

func (x *PlaylistTracksLengthRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

type PlaylistTracksLengthResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlaylistTracksLength *commonpb.TracksLength `protobuf:"bytes,1,opt,name=playlist_tracks_length,json=playlistTracksLength,proto3" json:"playlist_tracks_length,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlaylistTracksLengthResponse) Reset() {
	*x = PlaylistTracksLengthResponse{}
	mi := &file_proto_playlist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistTracksLengthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistTracksLengthResponse) ProtoMessage() {}

func (x *PlaylistTracksLengthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistTracksLengthResponse.ProtoReflect.Descriptor instead.
func (*PlaylistTracksLengthResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{14}
}

func (x *PlaylistTracksLengthResponse) GetPlaylistTracksLength() *commonpb.TracksLength {
	if x != nil {
		return x.PlaylistTracksLength
	}
	return nil
}

type GetPublicPlaylistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicPlaylistsRequest) Reset() {
	*x = GetPublicPlaylistsRequest{}
	mi := &file_proto_playlist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicPlaylistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicPlaylistsRequest) ProtoMessage() {}

func (x *GetPublicPlaylistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicPlaylistsRequest.ProtoReflect.Descriptor instead.
func (*GetPublicPlaylistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{15}
}

func (x *GetPublicPlaylistsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetPublicPlaylistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*commonpb.Playlist   `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicPlaylistsResponse) Reset() {
	*x = GetPublicPlaylistsResponse{}
	mi := &file_proto_playlist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicPlaylistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicPlaylistsResponse) ProtoMessage() {}

func (x *GetPublicPlaylistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicPlaylistsResponse.ProtoReflect.Descriptor instead.
func (*GetPublicPlaylistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{16}
}

func (x *GetPublicPlaylistsResponse) GetPlaylists() []*commonpb.Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

type RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlaylistTrackId string                 `protobuf:"bytes,1,opt,name=playlist_track_id,json=playlistTrackId,proto3" json:"playlist_track_id,omitempty"`
	NewPos          uint32                 `protobuf:"varint,2,opt,name=new_pos,json=newPos,proto3" json:"new_pos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) Reset() {
	*x = RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate{}
	mi := &file_proto_playlist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) ProtoMessage() {}

func (x *RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate.ProtoReflect.Descriptor instead.
func (*RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_rawDescGZIP(), []int{8, 0}
}

func (x *RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) GetPlaylistTrackId() string {
	if x != nil {
		return x.PlaylistTrackId
	}
	return ""
}

func (x *RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate) GetNewPos() uint32 {
	if x != nil {
		return x.NewPos
	}
	return 0
}

var File_proto_playlist_proto protoreflect.FileDescriptor

const file_proto_playlist_proto_rawDesc = "" +
	"\n" +
	"\x14proto/playlist.proto\x12\bplaylist\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12proto/common.proto\"k\n" +
	"\x13EditPlaylistRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcover_image\x18\x03 \x01(\tR\n" +
	"coverImage\":\n" +
	"\x15CreatePlaylistRequest\x12!\n" +
	"\fauthor_email\x18\x01 \x01(\tR\vauthorEmail\"8\n" +
	"\x17GetUserPlaylistsRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\"J\n" +
	"\x18GetUserPlaylistsResponse\x12.\n" +
	"\tplaylists\x18\x01 \x03(\v2\x10.common.PlaylistR\tplaylists\"9\n" +
	"\x16GetPlaylistByIdRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\"G\n" +
	"\x17GetPlaylistByIdResponse\x12,\n" +
	"\bplaylist\x18\x01 \x01(\v2\x10.common.PlaylistR\bplaylist\"\xec\x02\n" +
	"\x1dAddRemovePlaylistTrackRequest\x120\n" +
	"\aartists\x18\x01 \x03(\v2\x16.common.EmbeddedArtistR\aartists\x12\x1c\n" +
	"\tthumbnail\x18\x02 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12\x1f\n" +
	"\vis_explicit\x18\x04 \x01(\bR\n" +
	"isExplicit\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x19\n" +
	"\bvideo_id\x18\x06 \x01(\tR\avideoId\x120\n" +
	"\n" +
	"video_type\x18\a \x01(\x0e2\x11.common.VideoTypeR\tvideoType\x12\x1f\n" +
	"\vplaylist_id\x18\b \x01(\tR\n" +
	"playlistId\x120\n" +
	"\x05album\x18\t \x01(\v2\x15.common.EmbeddedAlbumH\x00R\x05album\x88\x01\x01B\b\n" +
	"\x06_album\"\x96\x02\n" +
	"\x1eAddRemovePlaylistTrackResponse\x12a\n" +
	"\vtoggle_type\x18\x01 \x01(\x0e2@.playlist.AddRemovePlaylistTrackResponse.PlaylistTrackToggleTypeR\n" +
	"toggleType\"\x90\x01\n" +
	"\x17PlaylistTrackToggleType\x12*\n" +
	"&PLAYLIST_TRACK_TOGGLE_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!PLAYLIST_TRACK_TOGGLE_TYPE_REMOVE\x10\x01\x12\"\n" +
	"\x1ePLAYLIST_TRACK_TOGGLE_TYPE_ADD\x10\x02\"\xfb\x01\n" +
	"\x1eRearrangePlaylistTracksRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12Y\n" +
	"\aupdates\x18\x02 \x03(\v2?.playlist.RearrangePlaylistTracksRequest.PlaylistTrackPosUpdateR\aupdates\x1a]\n" +
	"\x16PlaylistTrackPosUpdate\x12*\n" +
	"\x11playlist_track_id\x18\x01 \x01(\tR\x0fplaylistTrackId\x12\x17\n" +
	"\anew_pos\x18\x02 \x01(\rR\x06newPos\";\n" +
	"\x18GetPlaylistTracksRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\"[\n" +
	"\x19GetPlaylistTracksResponse\x12>\n" +
	"\x0fplaylist_tracks\x18\x01 \x03(\v2\x15.common.PlaylistTrackR\x0eplaylistTracks\"`\n" +
	"\x15DeletePlaylistRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12&\n" +
	"\x0fauth_user_email\x18\x02 \x01(\tR\rauthUserEmail\"j\n" +
	"\x1fChangePlaylistVisibilityRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12&\n" +
	"\x0fauth_user_email\x18\x02 \x01(\tR\rauthUserEmail\">\n" +
	"\x1bPlaylistTracksLengthRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\"j\n" +
	"\x1cPlaylistTracksLengthResponse\x12J\n" +
	"\x16playlist_tracks_length\x18\x01 \x01(\v2\x14.common.TracksLengthR\x14playlistTracksLength\"1\n" +
	"\x19GetPublicPlaylistsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"L\n" +
	"\x1aGetPublicPlaylistsResponse\x12.\n" +
	"\tplaylists\x18\x01 \x03(\v2\x10.common.PlaylistR\tplaylists2\xf3\a\n" +
	"\x0fPlaylistService\x12_\n" +
	"\x12GetPublicPlaylists\x12#.playlist.GetPublicPlaylistsRequest\x1a$.playlist.GetPublicPlaylistsResponse\x12h\n" +
	"\x17GetPlaylistTracksLength\x12%.playlist.PlaylistTracksLengthRequest\x1a&.playlist.PlaylistTracksLengthResponse\x12k\n" +
	"\x16AddRemovePlaylistTrack\x12'.playlist.AddRemovePlaylistTrackRequest\x1a(.playlist.AddRemovePlaylistTrackResponse\x12]\n" +
	"\x18ChangePlaylistVisibility\x12).playlist.ChangePlaylistVisibilityRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x17RearrangePlaylistTracks\x12(.playlist.RearrangePlaylistTracksRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eDeletePlaylist\x12\x1f.playlist.DeletePlaylistRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x11GetPlaylistTracks\x12\".playlist.GetPlaylistTracksRequest\x1a#.playlist.GetPlaylistTracksResponse\x12Y\n" +
	"\x10GetUserPlaylists\x12!.playlist.GetUserPlaylistsRequest\x1a\".playlist.GetUserPlaylistsResponse\x12V\n" +
	"\x0fGetPlaylistById\x12 .playlist.GetPlaylistByIdRequest\x1a!.playlist.GetPlaylistByIdResponse\x12E\n" +
	"\fEditPlaylist\x12\x1d.playlist.EditPlaylistRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eCreatePlaylist\x12\x1f.playlist.CreatePlaylistRequest\x1a\x16.google.protobuf.EmptyBAZ?github.com/Dev-Siri/wavelength/server/proto/playlist;playlistpbb\x06proto3"

var (
	file_proto_playlist_proto_rawDescOnce sync.Once
	file_proto_playlist_proto_rawDescData []byte
)

func file_proto_playlist_proto_rawDescGZIP() []byte {
	file_proto_playlist_proto_rawDescOnce.Do(func() {
		file_proto_playlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_playlist_proto_rawDesc), len(file_proto_playlist_proto_rawDesc)))
	})
	return file_proto_playlist_proto_rawDescData
}

var file_proto_playlist_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_playlist_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_playlist_proto_goTypes = []any{
	(AddRemovePlaylistTrackResponse_PlaylistTrackToggleType)(0),   // 0: playlist.AddRemovePlaylistTrackResponse.PlaylistTrackToggleType
	(*EditPlaylistRequest)(nil),                                   // 1: playlist.EditPlaylistRequest
	(*CreatePlaylistRequest)(nil),                                 // 2: playlist.CreatePlaylistRequest
	(*GetUserPlaylistsRequest)(nil),                               // 3: playlist.GetUserPlaylistsRequest
	(*GetUserPlaylistsResponse)(nil),                              // 4: playlist.GetUserPlaylistsResponse
	(*GetPlaylistByIdRequest)(nil),                                // 5: playlist.GetPlaylistByIdRequest
	(*GetPlaylistByIdResponse)(nil),                               // 6: playlist.GetPlaylistByIdResponse
	(*AddRemovePlaylistTrackRequest)(nil),                         // 7: playlist.AddRemovePlaylistTrackRequest
	(*AddRemovePlaylistTrackResponse)(nil),                        // 8: playlist.AddRemovePlaylistTrackResponse
	(*RearrangePlaylistTracksRequest)(nil),                        // 9: playlist.RearrangePlaylistTracksRequest
	(*GetPlaylistTracksRequest)(nil),                              // 10: playlist.GetPlaylistTracksRequest
	(*GetPlaylistTracksResponse)(nil),                             // 11: playlist.GetPlaylistTracksResponse
	(*DeletePlaylistRequest)(nil),                                 // 12: playlist.DeletePlaylistRequest
	(*ChangePlaylistVisibilityRequest)(nil),                       // 13: playlist.ChangePlaylistVisibilityRequest
	(*PlaylistTracksLengthRequest)(nil),                           // 14: playlist.PlaylistTracksLengthRequest
	(*PlaylistTracksLengthResponse)(nil),                          // 15: playlist.PlaylistTracksLengthResponse
	(*GetPublicPlaylistsRequest)(nil),                             // 16: playlist.GetPublicPlaylistsRequest
	(*GetPublicPlaylistsResponse)(nil),                            // 17: playlist.GetPublicPlaylistsResponse
	(*RearrangePlaylistTracksRequest_PlaylistTrackPosUpdate)(nil), // 18: playlist.RearrangePlaylistTracksRequest.PlaylistTrackPosUpdate
	(*commonpb.Playlist)(nil),                                     // 19: common.Playlist
	(*commonpb.EmbeddedArtist)(nil),                               // 20: common.EmbeddedArtist
	(commonpb.VideoType)(0),                                       // 21: common.VideoType
	(*commonpb.EmbeddedAlbum)(nil),                                // 22: common.EmbeddedAlbum
	(*commonpb.PlaylistTrack)(nil),                                // 23: common.PlaylistTrack
	(*commonpb.TracksLength)(nil),                                 // 24: common.TracksLength
	(*emptypb.Empty)(nil),                                         // 25: google.protobuf.Empty
}
var file_proto_playlist_proto_depIdxs = []int32{
	19, // 0: playlist.GetUserPlaylistsResponse.playlists:type_name -> common.Playlist
	19, // 1: playlist.GetPlaylistByIdResponse.playlist:type_name -> common.Playlist
	20, // 2: playlist.AddRemovePlaylistTrackRequest.artists:type_name -> common.EmbeddedArtist
	21, // 3: playlist.AddRemovePlaylistTrackRequest.video_type:type_name -> common.VideoType
	22, // 4: playlist.AddRemovePlaylistTrackRequest.album:type_name -> common.EmbeddedAlbum
	0,  // 5: playlist.AddRemovePlaylistTrackResponse.toggle_type:type_name -> playlist.AddRemovePlaylistTrackResponse.PlaylistTrackToggleType
	18, // 6: playlist.RearrangePlaylistTracksRequest.updates:type_name -> playlist.RearrangePlaylistTracksRequest.PlaylistTrackPosUpdate
	23, // 7: playlist.GetPlaylistTracksResponse.playlist_tracks:type_name -> common.PlaylistTrack
	24, // 8: playlist.PlaylistTracksLengthResponse.playlist_tracks_length:type_name -> common.TracksLength
	19, // 9: playlist.GetPublicPlaylistsResponse.playlists:type_name -> common.Playlist
	16, // 10: playlist.PlaylistService.GetPublicPlaylists:input_type -> playlist.GetPublicPlaylistsRequest
	14, // 11: playlist.PlaylistService.GetPlaylistTracksLength:input_type -> playlist.PlaylistTracksLengthRequest
	7,  // 12: playlist.PlaylistService.AddRemovePlaylistTrack:input_type -> playlist.AddRemovePlaylistTrackRequest
	13, // 13: playlist.PlaylistService.ChangePlaylistVisibility:input_type -> playlist.ChangePlaylistVisibilityRequest
	9,  // 14: playlist.PlaylistService.RearrangePlaylistTracks:input_type -> playlist.RearrangePlaylistTracksRequest
	12, // 15: playlist.PlaylistService.DeletePlaylist:input_type -> playlist.DeletePlaylistRequest
	10, // 16: playlist.PlaylistService.GetPlaylistTracks:input_type -> playlist.GetPlaylistTracksRequest
	3,  // 17: playlist.PlaylistService.GetUserPlaylists:input_type -> playlist.GetUserPlaylistsRequest
	5,  // 18: playlist.PlaylistService.GetPlaylistById:input_type -> playlist.GetPlaylistByIdRequest
	1,  // 19: playlist.PlaylistService.EditPlaylist:input_type -> playlist.EditPlaylistRequest
	2,  // 20: playlist.PlaylistService.CreatePlaylist:input_type -> playlist.CreatePlaylistRequest
	17, // 21: playlist.PlaylistService.GetPublicPlaylists:output_type -> playlist.GetPublicPlaylistsResponse
	15, // 22: playlist.PlaylistService.GetPlaylistTracksLength:output_type -> playlist.PlaylistTracksLengthResponse
	8,  // 23: playlist.PlaylistService.AddRemovePlaylistTrack:output_type -> playlist.AddRemovePlaylistTrackResponse
	25, // 24: playlist.PlaylistService.ChangePlaylistVisibility:output_type -> google.protobuf.Empty
	25, // 25: playlist.PlaylistService.RearrangePlaylistTracks:output_type -> google.protobuf.Empty
	25, // 26: playlist.PlaylistService.DeletePlaylist:output_type -> google.protobuf.Empty
	11, // 27: playlist.PlaylistService.GetPlaylistTracks:output_type -> playlist.GetPlaylistTracksResponse
	4,  // 28: playlist.PlaylistService.GetUserPlaylists:output_type -> playlist.GetUserPlaylistsResponse
	6,  // 29: playlist.PlaylistService.GetPlaylistById:output_type -> playlist.GetPlaylistByIdResponse
	25, // 30: playlist.PlaylistService.EditPlaylist:output_type -> google.protobuf.Empty
	25, // 31: playlist.PlaylistService.CreatePlaylist:output_type -> google.protobuf.Empty
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_playlist_proto_init() }
func file_proto_playlist_proto_init() {
	if File_proto_playlist_proto != nil {
		return
	}
	file_proto_playlist_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_playlist_proto_rawDesc), len(file_proto_playlist_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_playlist_proto_goTypes,
		DependencyIndexes: file_proto_playlist_proto_depIdxs,
		EnumInfos:         file_proto_playlist_proto_enumTypes,
		MessageInfos:      file_proto_playlist_proto_msgTypes,
	}.Build()
	File_proto_playlist_proto = out.File
	file_proto_playlist_proto_goTypes = nil
	file_proto_playlist_proto_depIdxs = nil
}
