name: wavelength
description: "Call this a glorified YT Music Wrapper."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.5
  go_router: ^14.6.3
  http: ^1.3.0
  cached_network_image: ^3.4.1
  shimmer_animation: ^2.2.2
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.2
  youtube_explode_dart: ^2.5.2
  just_audio_background: ^0.0.1-beta.17
  just_audio: ^0.10.4
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  country_flags: ^3.0.0
  html_unescape: ^2.0.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  image_picker: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  mini_music_visualizer: ^1.1.4
  url_launcher: ^6.3.2
  flutter_bloc: ^9.0.0
  lucide_icons_flutter: ^1.2.7
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  vector_graphics_compiler: ^1.1.16
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/vectors/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
