// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/yt_scraper.proto

package yt_scraperpb

import (
	commonpb "github.com/Dev-Siri/wavelength/server/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSearchSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchSuggestionsRequest) Reset() {
	*x = GetSearchSuggestionsRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchSuggestionsRequest) ProtoMessage() {}

func (x *GetSearchSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetSearchSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *GetSearchSuggestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetSearchSuggestionsResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SuggestedQueries []string                  `protobuf:"bytes,1,rep,name=suggested_queries,json=suggestedQueries,proto3" json:"suggested_queries,omitempty"`
	SuggestedLinks   []*commonpb.SuggestedLink `protobuf:"bytes,2,rep,name=suggested_links,json=suggestedLinks,proto3" json:"suggested_links,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSearchSuggestionsResponse) Reset() {
	*x = GetSearchSuggestionsResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchSuggestionsResponse) ProtoMessage() {}

func (x *GetSearchSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetSearchSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchSuggestionsResponse) GetSuggestedQueries() []string {
	if x != nil {
		return x.SuggestedQueries
	}
	return nil
}

func (x *GetSearchSuggestionsResponse) GetSuggestedLinks() []*commonpb.SuggestedLink {
	if x != nil {
		return x.SuggestedLinks
	}
	return nil
}

type GetQuickPicksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region/Country code. (Like US, UK, IN)
	Gl            string `protobuf:"bytes,1,opt,name=gl,proto3" json:"gl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickPicksRequest) Reset() {
	*x = GetQuickPicksRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickPicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickPicksRequest) ProtoMessage() {}

func (x *GetQuickPicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickPicksRequest.ProtoReflect.Descriptor instead.
func (*GetQuickPicksRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuickPicksRequest) GetGl() string {
	if x != nil {
		return x.Gl
	}
	return ""
}

type GetQuickPicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuickPicks    []*commonpb.QuickPick  `protobuf:"bytes,1,rep,name=quick_picks,json=quickPicks,proto3" json:"quick_picks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickPicksResponse) Reset() {
	*x = GetQuickPicksResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickPicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickPicksResponse) ProtoMessage() {}

func (x *GetQuickPicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickPicksResponse.ProtoReflect.Descriptor instead.
func (*GetQuickPicksResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuickPicksResponse) GetQuickPicks() []*commonpb.QuickPick {
	if x != nil {
		return x.QuickPicks
	}
	return nil
}

type SearchTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracksRequest) Reset() {
	*x = SearchTracksRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracksRequest) ProtoMessage() {}

func (x *SearchTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracksRequest.ProtoReflect.Descriptor instead.
func (*SearchTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *SearchTracksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*commonpb.Track      `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracksResponse) Reset() {
	*x = SearchTracksResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracksResponse) ProtoMessage() {}

func (x *SearchTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracksResponse.ProtoReflect.Descriptor instead.
func (*SearchTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *SearchTracksResponse) GetTracks() []*commonpb.Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetAlbumDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       string                 `protobuf:"bytes,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumDetailsRequest) Reset() {
	*x = GetAlbumDetailsRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumDetailsRequest) ProtoMessage() {}

func (x *GetAlbumDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *GetAlbumDetailsRequest) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

type GetAlbumDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *commonpb.Album        `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumDetailsResponse) Reset() {
	*x = GetAlbumDetailsResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumDetailsResponse) ProtoMessage() {}

func (x *GetAlbumDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *GetAlbumDetailsResponse) GetAlbum() *commonpb.Album {
	if x != nil {
		return x.Album
	}
	return nil
}

type SearchArtistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistsRequest) Reset() {
	*x = SearchArtistsRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistsRequest) ProtoMessage() {}

func (x *SearchArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistsRequest.ProtoReflect.Descriptor instead.
func (*SearchArtistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *SearchArtistsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchArtistsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Artists       []*commonpb.SearchArtist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistsResponse) Reset() {
	*x = SearchArtistsResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistsResponse) ProtoMessage() {}

func (x *SearchArtistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistsResponse.ProtoReflect.Descriptor instead.
func (*SearchArtistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{9}
}

func (x *SearchArtistsResponse) GetArtists() []*commonpb.SearchArtist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type SearchAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAlbumsRequest) Reset() {
	*x = SearchAlbumsRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlbumsRequest) ProtoMessage() {}

func (x *SearchAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlbumsRequest.ProtoReflect.Descriptor instead.
func (*SearchAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *SearchAlbumsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchAlbumsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Albums        []*commonpb.SearchAlbum `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAlbumsResponse) Reset() {
	*x = SearchAlbumsResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlbumsResponse) ProtoMessage() {}

func (x *SearchAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlbumsResponse.ProtoReflect.Descriptor instead.
func (*SearchAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *SearchAlbumsResponse) GetAlbums() []*commonpb.SearchAlbum {
	if x != nil {
		return x.Albums
	}
	return nil
}

type GetArtistDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowseId      string                 `protobuf:"bytes,1,opt,name=browse_id,json=browseId,proto3" json:"browse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistDetailsRequest) Reset() {
	*x = GetArtistDetailsRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistDetailsRequest) ProtoMessage() {}

func (x *GetArtistDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetArtistDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *GetArtistDetailsRequest) GetBrowseId() string {
	if x != nil {
		return x.BrowseId
	}
	return ""
}

type GetArtistDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *commonpb.Artist       `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistDetailsResponse) Reset() {
	*x = GetArtistDetailsResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistDetailsResponse) ProtoMessage() {}

func (x *GetArtistDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetArtistDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *GetArtistDetailsResponse) GetArtist() *commonpb.Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type SearchYouTubeVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchYouTubeVideosRequest) Reset() {
	*x = SearchYouTubeVideosRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchYouTubeVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchYouTubeVideosRequest) ProtoMessage() {}

func (x *SearchYouTubeVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchYouTubeVideosRequest.ProtoReflect.Descriptor instead.
func (*SearchYouTubeVideosRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{14}
}

func (x *SearchYouTubeVideosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchYouTubeVideosResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Videos        []*commonpb.YouTubeVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchYouTubeVideosResponse) Reset() {
	*x = SearchYouTubeVideosResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchYouTubeVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchYouTubeVideosResponse) ProtoMessage() {}

func (x *SearchYouTubeVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchYouTubeVideosResponse.ProtoReflect.Descriptor instead.
func (*SearchYouTubeVideosResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{15}
}

func (x *SearchYouTubeVideosResponse) GetVideos() []*commonpb.YouTubeVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_proto_yt_scraper_proto protoreflect.FileDescriptor

const file_proto_yt_scraper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/yt_scraper.proto\x12\n" +
	"yt_scraper\x1a\x12proto/common.proto\"3\n" +
	"\x1bGetSearchSuggestionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x8b\x01\n" +
	"\x1cGetSearchSuggestionsResponse\x12+\n" +
	"\x11suggested_queries\x18\x01 \x03(\tR\x10suggestedQueries\x12>\n" +
	"\x0fsuggested_links\x18\x02 \x03(\v2\x15.common.SuggestedLinkR\x0esuggestedLinks\"&\n" +
	"\x14GetQuickPicksRequest\x12\x0e\n" +
	"\x02gl\x18\x01 \x01(\tR\x02gl\"K\n" +
	"\x15GetQuickPicksResponse\x122\n" +
	"\vquick_picks\x18\x01 \x03(\v2\x11.common.QuickPickR\n" +
	"quickPicks\"+\n" +
	"\x13SearchTracksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"=\n" +
	"\x14SearchTracksResponse\x12%\n" +
	"\x06tracks\x18\x01 \x03(\v2\r.common.TrackR\x06tracks\"3\n" +
	"\x16GetAlbumDetailsRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\tR\aalbumId\">\n" +
	"\x17GetAlbumDetailsResponse\x12#\n" +
	"\x05album\x18\x01 \x01(\v2\r.common.AlbumR\x05album\",\n" +
	"\x14SearchArtistsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"G\n" +
	"\x15SearchArtistsResponse\x12.\n" +
	"\aartists\x18\x01 \x03(\v2\x14.common.SearchArtistR\aartists\"+\n" +
	"\x13SearchAlbumsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"C\n" +
	"\x14SearchAlbumsResponse\x12+\n" +
	"\x06albums\x18\x01 \x03(\v2\x13.common.SearchAlbumR\x06albums\"6\n" +
	"\x17GetArtistDetailsRequest\x12\x1b\n" +
	"\tbrowse_id\x18\x01 \x01(\tR\bbrowseId\"B\n" +
	"\x18GetArtistDetailsResponse\x12&\n" +
	"\x06artist\x18\x01 \x01(\v2\x0e.common.ArtistR\x06artist\"2\n" +
	"\x1aSearchYouTubeVideosRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"K\n" +
	"\x1bSearchYouTubeVideosResponse\x12,\n" +
	"\x06videos\x18\x01 \x03(\v2\x14.common.YouTubeVideoR\x06videos2\xeb\x05\n" +
	"\tYTScraper\x12i\n" +
	"\x14GetSearchSuggestions\x12'.yt_scraper.GetSearchSuggestionsRequest\x1a(.yt_scraper.GetSearchSuggestionsResponse\x12T\n" +
	"\rGetQuickPicks\x12 .yt_scraper.GetQuickPicksRequest\x1a!.yt_scraper.GetQuickPicksResponse\x12Z\n" +
	"\x0fGetAlbumDetails\x12\".yt_scraper.GetAlbumDetailsRequest\x1a#.yt_scraper.GetAlbumDetailsResponse\x12]\n" +
	"\x10GetArtistDetails\x12#.yt_scraper.GetArtistDetailsRequest\x1a$.yt_scraper.GetArtistDetailsResponse\x12Q\n" +
	"\fSearchTracks\x12\x1f.yt_scraper.SearchTracksRequest\x1a .yt_scraper.SearchTracksResponse\x12T\n" +
	"\rSearchArtists\x12 .yt_scraper.SearchArtistsRequest\x1a!.yt_scraper.SearchArtistsResponse\x12Q\n" +
	"\fSearchAlbums\x12\x1f.yt_scraper.SearchAlbumsRequest\x1a .yt_scraper.SearchAlbumsResponse\x12f\n" +
	"\x13SearchYouTubeVideos\x12&.yt_scraper.SearchYouTubeVideosRequest\x1a'.yt_scraper.SearchYouTubeVideosResponseBEZCgithub.com/Dev-Siri/wavelength/server/proto/yt_scraper;yt_scraperpbb\x06proto3"

var (
	file_proto_yt_scraper_proto_rawDescOnce sync.Once
	file_proto_yt_scraper_proto_rawDescData []byte
)

func file_proto_yt_scraper_proto_rawDescGZIP() []byte {
	file_proto_yt_scraper_proto_rawDescOnce.Do(func() {
		file_proto_yt_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yt_scraper_proto_rawDesc), len(file_proto_yt_scraper_proto_rawDesc)))
	})
	return file_proto_yt_scraper_proto_rawDescData
}

var file_proto_yt_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_yt_scraper_proto_goTypes = []any{
	(*GetSearchSuggestionsRequest)(nil),  // 0: yt_scraper.GetSearchSuggestionsRequest
	(*GetSearchSuggestionsResponse)(nil), // 1: yt_scraper.GetSearchSuggestionsResponse
	(*GetQuickPicksRequest)(nil),         // 2: yt_scraper.GetQuickPicksRequest
	(*GetQuickPicksResponse)(nil),        // 3: yt_scraper.GetQuickPicksResponse
	(*SearchTracksRequest)(nil),          // 4: yt_scraper.SearchTracksRequest
	(*SearchTracksResponse)(nil),         // 5: yt_scraper.SearchTracksResponse
	(*GetAlbumDetailsRequest)(nil),       // 6: yt_scraper.GetAlbumDetailsRequest
	(*GetAlbumDetailsResponse)(nil),      // 7: yt_scraper.GetAlbumDetailsResponse
	(*SearchArtistsRequest)(nil),         // 8: yt_scraper.SearchArtistsRequest
	(*SearchArtistsResponse)(nil),        // 9: yt_scraper.SearchArtistsResponse
	(*SearchAlbumsRequest)(nil),          // 10: yt_scraper.SearchAlbumsRequest
	(*SearchAlbumsResponse)(nil),         // 11: yt_scraper.SearchAlbumsResponse
	(*GetArtistDetailsRequest)(nil),      // 12: yt_scraper.GetArtistDetailsRequest
	(*GetArtistDetailsResponse)(nil),     // 13: yt_scraper.GetArtistDetailsResponse
	(*SearchYouTubeVideosRequest)(nil),   // 14: yt_scraper.SearchYouTubeVideosRequest
	(*SearchYouTubeVideosResponse)(nil),  // 15: yt_scraper.SearchYouTubeVideosResponse
	(*commonpb.SuggestedLink)(nil),       // 16: common.SuggestedLink
	(*commonpb.QuickPick)(nil),           // 17: common.QuickPick
	(*commonpb.Track)(nil),               // 18: common.Track
	(*commonpb.Album)(nil),               // 19: common.Album
	(*commonpb.SearchArtist)(nil),        // 20: common.SearchArtist
	(*commonpb.SearchAlbum)(nil),         // 21: common.SearchAlbum
	(*commonpb.Artist)(nil),              // 22: common.Artist
	(*commonpb.YouTubeVideo)(nil),        // 23: common.YouTubeVideo
}
var file_proto_yt_scraper_proto_depIdxs = []int32{
	16, // 0: yt_scraper.GetSearchSuggestionsResponse.suggested_links:type_name -> common.SuggestedLink
	17, // 1: yt_scraper.GetQuickPicksResponse.quick_picks:type_name -> common.QuickPick
	18, // 2: yt_scraper.SearchTracksResponse.tracks:type_name -> common.Track
	19, // 3: yt_scraper.GetAlbumDetailsResponse.album:type_name -> common.Album
	20, // 4: yt_scraper.SearchArtistsResponse.artists:type_name -> common.SearchArtist
	21, // 5: yt_scraper.SearchAlbumsResponse.albums:type_name -> common.SearchAlbum
	22, // 6: yt_scraper.GetArtistDetailsResponse.artist:type_name -> common.Artist
	23, // 7: yt_scraper.SearchYouTubeVideosResponse.videos:type_name -> common.YouTubeVideo
	0,  // 8: yt_scraper.YTScraper.GetSearchSuggestions:input_type -> yt_scraper.GetSearchSuggestionsRequest
	2,  // 9: yt_scraper.YTScraper.GetQuickPicks:input_type -> yt_scraper.GetQuickPicksRequest
	6,  // 10: yt_scraper.YTScraper.GetAlbumDetails:input_type -> yt_scraper.GetAlbumDetailsRequest
	12, // 11: yt_scraper.YTScraper.GetArtistDetails:input_type -> yt_scraper.GetArtistDetailsRequest
	4,  // 12: yt_scraper.YTScraper.SearchTracks:input_type -> yt_scraper.SearchTracksRequest
	8,  // 13: yt_scraper.YTScraper.SearchArtists:input_type -> yt_scraper.SearchArtistsRequest
	10, // 14: yt_scraper.YTScraper.SearchAlbums:input_type -> yt_scraper.SearchAlbumsRequest
	14, // 15: yt_scraper.YTScraper.SearchYouTubeVideos:input_type -> yt_scraper.SearchYouTubeVideosRequest
	1,  // 16: yt_scraper.YTScraper.GetSearchSuggestions:output_type -> yt_scraper.GetSearchSuggestionsResponse
	3,  // 17: yt_scraper.YTScraper.GetQuickPicks:output_type -> yt_scraper.GetQuickPicksResponse
	7,  // 18: yt_scraper.YTScraper.GetAlbumDetails:output_type -> yt_scraper.GetAlbumDetailsResponse
	13, // 19: yt_scraper.YTScraper.GetArtistDetails:output_type -> yt_scraper.GetArtistDetailsResponse
	5,  // 20: yt_scraper.YTScraper.SearchTracks:output_type -> yt_scraper.SearchTracksResponse
	9,  // 21: yt_scraper.YTScraper.SearchArtists:output_type -> yt_scraper.SearchArtistsResponse
	11, // 22: yt_scraper.YTScraper.SearchAlbums:output_type -> yt_scraper.SearchAlbumsResponse
	15, // 23: yt_scraper.YTScraper.SearchYouTubeVideos:output_type -> yt_scraper.SearchYouTubeVideosResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_yt_scraper_proto_init() }
func file_proto_yt_scraper_proto_init() {
	if File_proto_yt_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yt_scraper_proto_rawDesc), len(file_proto_yt_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_yt_scraper_proto_goTypes,
		DependencyIndexes: file_proto_yt_scraper_proto_depIdxs,
		MessageInfos:      file_proto_yt_scraper_proto_msgTypes,
	}.Build()
	File_proto_yt_scraper_proto = out.File
	file_proto_yt_scraper_proto_goTypes = nil
	file_proto_yt_scraper_proto_depIdxs = nil
}
