// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/yt_scraper.proto

package yt_scraperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	commonpb "wavelength/proto/commonpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSearchSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchSuggestionsRequest) Reset() {
	*x = GetSearchSuggestionsRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchSuggestionsRequest) ProtoMessage() {}

func (x *GetSearchSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetSearchSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *GetSearchSuggestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetSearchSuggestionsResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SuggestedQueries []string                  `protobuf:"bytes,1,rep,name=suggested_queries,json=suggestedQueries,proto3" json:"suggested_queries,omitempty"`
	SuggestedLinks   []*commonpb.SuggestedLink `protobuf:"bytes,2,rep,name=suggested_links,json=suggestedLinks,proto3" json:"suggested_links,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSearchSuggestionsResponse) Reset() {
	*x = GetSearchSuggestionsResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchSuggestionsResponse) ProtoMessage() {}

func (x *GetSearchSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetSearchSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchSuggestionsResponse) GetSuggestedQueries() []string {
	if x != nil {
		return x.SuggestedQueries
	}
	return nil
}

func (x *GetSearchSuggestionsResponse) GetSuggestedLinks() []*commonpb.SuggestedLink {
	if x != nil {
		return x.SuggestedLinks
	}
	return nil
}

type GetQuickPicksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region/Country code. (Like US, UK, IN)
	Gl            string `protobuf:"bytes,1,opt,name=gl,proto3" json:"gl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickPicksRequest) Reset() {
	*x = GetQuickPicksRequest{}
	mi := &file_proto_yt_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickPicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickPicksRequest) ProtoMessage() {}

func (x *GetQuickPicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickPicksRequest.ProtoReflect.Descriptor instead.
func (*GetQuickPicksRequest) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuickPicksRequest) GetGl() string {
	if x != nil {
		return x.Gl
	}
	return ""
}

type GetQuickPicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuickPicks    []*commonpb.QuickPick  `protobuf:"bytes,1,rep,name=quick_picks,json=quickPicks,proto3" json:"quick_picks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickPicksResponse) Reset() {
	*x = GetQuickPicksResponse{}
	mi := &file_proto_yt_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickPicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickPicksResponse) ProtoMessage() {}

func (x *GetQuickPicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yt_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickPicksResponse.ProtoReflect.Descriptor instead.
func (*GetQuickPicksResponse) Descriptor() ([]byte, []int) {
	return file_proto_yt_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuickPicksResponse) GetQuickPicks() []*commonpb.QuickPick {
	if x != nil {
		return x.QuickPicks
	}
	return nil
}

var File_proto_yt_scraper_proto protoreflect.FileDescriptor

const file_proto_yt_scraper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/yt_scraper.proto\x12\n" +
	"yt_scraper\x1a\x12proto/common.proto\"3\n" +
	"\x1bGetSearchSuggestionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x8b\x01\n" +
	"\x1cGetSearchSuggestionsResponse\x12+\n" +
	"\x11suggested_queries\x18\x01 \x03(\tR\x10suggestedQueries\x12>\n" +
	"\x0fsuggested_links\x18\x02 \x03(\v2\x15.common.SuggestedLinkR\x0esuggestedLinks\"&\n" +
	"\x14GetQuickPicksRequest\x12\x0e\n" +
	"\x02gl\x18\x01 \x01(\tR\x02gl\"K\n" +
	"\x15GetQuickPicksResponse\x122\n" +
	"\vquick_picks\x18\x01 \x03(\v2\x11.common.QuickPickR\n" +
	"quickPicks2\xcc\x01\n" +
	"\tYTScraper\x12i\n" +
	"\x14GetSearchSuggestions\x12'.yt_scraper.GetSearchSuggestionsRequest\x1a(.yt_scraper.GetSearchSuggestionsResponse\x12T\n" +
	"\rGetQuickPicks\x12 .yt_scraper.GetQuickPicksRequest\x1a!.yt_scraper.GetQuickPicksResponseB1Z/wavelength/server/proto/yt_scraper;yt_scraperpbb\x06proto3"

var (
	file_proto_yt_scraper_proto_rawDescOnce sync.Once
	file_proto_yt_scraper_proto_rawDescData []byte
)

func file_proto_yt_scraper_proto_rawDescGZIP() []byte {
	file_proto_yt_scraper_proto_rawDescOnce.Do(func() {
		file_proto_yt_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yt_scraper_proto_rawDesc), len(file_proto_yt_scraper_proto_rawDesc)))
	})
	return file_proto_yt_scraper_proto_rawDescData
}

var file_proto_yt_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_yt_scraper_proto_goTypes = []any{
	(*GetSearchSuggestionsRequest)(nil),  // 0: yt_scraper.GetSearchSuggestionsRequest
	(*GetSearchSuggestionsResponse)(nil), // 1: yt_scraper.GetSearchSuggestionsResponse
	(*GetQuickPicksRequest)(nil),         // 2: yt_scraper.GetQuickPicksRequest
	(*GetQuickPicksResponse)(nil),        // 3: yt_scraper.GetQuickPicksResponse
	(*commonpb.SuggestedLink)(nil),       // 4: common.SuggestedLink
	(*commonpb.QuickPick)(nil),           // 5: common.QuickPick
}
var file_proto_yt_scraper_proto_depIdxs = []int32{
	4, // 0: yt_scraper.GetSearchSuggestionsResponse.suggested_links:type_name -> common.SuggestedLink
	5, // 1: yt_scraper.GetQuickPicksResponse.quick_picks:type_name -> common.QuickPick
	0, // 2: yt_scraper.YTScraper.GetSearchSuggestions:input_type -> yt_scraper.GetSearchSuggestionsRequest
	2, // 3: yt_scraper.YTScraper.GetQuickPicks:input_type -> yt_scraper.GetQuickPicksRequest
	1, // 4: yt_scraper.YTScraper.GetSearchSuggestions:output_type -> yt_scraper.GetSearchSuggestionsResponse
	3, // 5: yt_scraper.YTScraper.GetQuickPicks:output_type -> yt_scraper.GetQuickPicksResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_yt_scraper_proto_init() }
func file_proto_yt_scraper_proto_init() {
	if File_proto_yt_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yt_scraper_proto_rawDesc), len(file_proto_yt_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_yt_scraper_proto_goTypes,
		DependencyIndexes: file_proto_yt_scraper_proto_depIdxs,
		MessageInfos:      file_proto_yt_scraper_proto_msgTypes,
	}.Build()
	File_proto_yt_scraper_proto = out.File
	file_proto_yt_scraper_proto_goTypes = nil
	file_proto_yt_scraper_proto_depIdxs = nil
}
