// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/yt_scraper.proto

package yt_scraperpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YTScraper_GetSearchSuggestions_FullMethodName = "/yt_scraper.YTScraper/GetSearchSuggestions"
)

// YTScraperClient is the client API for YTScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YTScraperClient interface {
	GetSearchSuggestions(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type yTScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewYTScraperClient(cc grpc.ClientConnInterface) YTScraperClient {
	return &yTScraperClient{cc}
}

func (c *yTScraperClient) GetSearchSuggestions(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, YTScraper_GetSearchSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YTScraperServer is the server API for YTScraper service.
// All implementations must embed UnimplementedYTScraperServer
// for forward compatibility.
type YTScraperServer interface {
	GetSearchSuggestions(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedYTScraperServer()
}

// UnimplementedYTScraperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYTScraperServer struct{}

func (UnimplementedYTScraperServer) GetSearchSuggestions(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSearchSuggestions not implemented")
}
func (UnimplementedYTScraperServer) mustEmbedUnimplementedYTScraperServer() {}
func (UnimplementedYTScraperServer) testEmbeddedByValue()                   {}

// UnsafeYTScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YTScraperServer will
// result in compilation errors.
type UnsafeYTScraperServer interface {
	mustEmbedUnimplementedYTScraperServer()
}

func RegisterYTScraperServer(s grpc.ServiceRegistrar, srv YTScraperServer) {
	// If the following call panics, it indicates UnimplementedYTScraperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YTScraper_ServiceDesc, srv)
}

func _YTScraper_GetSearchSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTScraperServer).GetSearchSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YTScraper_GetSearchSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTScraperServer).GetSearchSuggestions(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YTScraper_ServiceDesc is the grpc.ServiceDesc for YTScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YTScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yt_scraper.YTScraper",
	HandlerType: (*YTScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSearchSuggestions",
			Handler:    _YTScraper_GetSearchSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/yt_scraper.proto",
}
