services:
  gateway:
    mem_limit: 512m
    cpus: 1
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/gateway/Dockerfile
    image: wavelength/services/gateway
    container_name: gateway
    ports:
      - "8080:8000"
    env_file: services/gateway/.env
    environment:
      - PORT=8000
      - PLAYLIST_CLIENT_URL=playlist:8081
      - MUSIC_CLIENT_URL=music:8082
      - ARTIST_CLIENT_URL=artist:8084
      - ALBUM_CLIENT_URL=album:8085
      - IMAGE_CLIENT_URL=image:8086
      - AUTH_CLIENT_URL=auth:8087
      - LYRIC_CLIENT_URL=lyrics:8088
      - GO_ENV=dev
    depends_on:
      - playlist
      - music
      - artist
      - album
      - image
      - auth
      - lyrics
    develop:
      watch:
        - action: rebuild
          path: services/gateway
  playlist:
    mem_limit: 256m
    cpus: 0.25
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/playlist/Dockerfile
    image: wavelength/services/playlist
    container_name: playlist
    env_file: services/playlist/.env
    environment:
      - PORT=8081
      - ARTIST_CLIENT_URL=artist:8084
      - ALBUM_CLIENT_URL=album:8085
      - YT_SCRAPER_URL=yt-scraper:8083
      - GO_ENV=dev
    depends_on:
      - artist
      - album
      - yt-scraper
    develop:
      watch:
        - action: rebuild
          path: services
  music:
    mem_limit: 256m
    cpus: 1
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/music/Dockerfile
    image: wavelength/services/music
    container_name: music
    env_file: services/music/.env
    environment:
      - PORT=8082
      - YT_SCRAPER_URL=yt-scraper:8083
      - ARTIST_CLIENT_URL=artist:8084
      - ALBUM_CLIENT_URL=album:8085
      - GO_ENV=dev
    depends_on:
      - yt-scraper
      - artist
      - album
    develop:
      watch:
        - action: rebuild
          path: services
  yt-scraper:
    mem_limit: 512m
    cpus: 1
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/yt-scraper/Dockerfile
    image: wavelength/services/yt-scraper
    container_name: yt-scraper
    env_file: services/yt-scraper/.env
    environment:
      - PORT=8083
      - NODE_ENV=production
    develop:
      watch:
        - action: sync
          path: services/yt-scraper
          target: /app
        - action: rebuild
          path: services/yt-scraper/package.json
  artist:
    mem_limit: 128m
    cpus: 0.25
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/artist/Dockerfile
    image: wavelength/services/artist
    container_name: artist
    env_file: services/artist/.env
    environment:
      - PORT=8084
      - YT_SCRAPER_URL=yt-scraper:8083
      - GO_ENV=dev
    depends_on:
      - yt-scraper
    develop:
      watch:
        - action: rebuild
          path: services
  album:
    mem_limit: 128m
    cpus: 0.25
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/album/Dockerfile
    image: wavelength/services/album
    container_name: album
    env_file: services/album/.env
    environment:
      - PORT=8085
      - YT_SCRAPER_URL=yt-scraper:8083
      - GO_ENV=dev
    depends_on:
      - yt-scraper
    develop:
      watch:
        - action: rebuild
          path: services
  auth:
    mem_limit: 256m
    cpus: 0.25
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/auth/Dockerfile
    image: wavelength/services/auth
    container_name: auth
    env_file: services/auth/.env
    environment:
      - PORT=8087
      - GO_ENV=dev
    develop:
      watch:
        - action: rebuild
          path: services
  image:
    mem_limit: 1g
    cpus: 1
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/image/Dockerfile
    image: wavelength/services/image
    container_name: image
    environment:
      - PORT=8086
      - GO_ENV=dev
    develop:
      watch:
        - action: rebuild
          path: services
  lyrics:
    mem_limit: 128m
    cpus: 0.25
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/lyrics/Dockerfile
    image: wavelength/services/lyrics
    container_name: lyrics
    env_file: services/lyrics/.env
    environment:
      - PORT=8088
      - YT_SCRAPER_URL=yt-scraper:8083
      - GO_ENV=dev
    depends_on:
      - yt-scraper
    develop:
      watch:
        - action: rebuild
          path: services
  player:
    mem_limit: 256m
    cpus: 1
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/player/Dockerfile
    image: wavelength/services/player
    container_name: player
    env_file: services/player/.env
    environment:
      - PORT=8000
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - GO_ENV=dev
      - COLLECTOR_CLIENT_URL=collector:8089
      - YT_SCRAPER_URL=yt-scraper:8083
    ports:
      - "8000:8000"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - collector
      - yt-scraper
    develop:
      watch:
        - action: rebuild
          path: services
  collector:
    mem_limit: 2g
    cpus: 1
    build:
      platforms:
        - linux/amd64
      context: .
      dockerfile: services/collector/Dockerfile
    image: wavelength/services/collector
    container_name: collector
    env_file: services/collector/.env
    environment:
      - PORT=8089
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - GO_ENV=dev
      - YT_SCRAPER_URL=yt-scraper:8083
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - yt-scraper
    develop:
      watch:
        - action: rebuild
          path: services
