import "package:hive/hive.dart";
import "package:wavelength/api/models/album.dart";
import "package:wavelength/api/models/artist.dart";
import "package:wavelength/api/models/auth_user.dart";
import "package:wavelength/api/models/embedded.dart";
import "package:wavelength/api/models/enums/album_type.dart";
import "package:wavelength/api/models/enums/alignment_direction.dart";
import "package:wavelength/api/models/enums/lossless_availability.dart";
import "package:wavelength/api/models/enums/playability_status.dart";
import "package:wavelength/api/models/enums/video_type.dart";
import "package:wavelength/api/models/liked_track.dart";
import "package:wavelength/api/models/lyrics_line.dart";
import "package:wavelength/api/models/playlist.dart";
import "package:wavelength/api/models/playlist_track.dart";
import "package:wavelength/api/models/playlist_tracks_length.dart";
import "package:wavelength/api/models/saved_album.dart";
import "package:wavelength/api/models/stream.dart";
import "package:wavelength/api/models/theme_color.dart";
import "package:wavelength/api/models/track.dart";
import "package:wavelength/audio/queueable_music.dart";

void registerHiveAdapters() {
  Hive.registerAdapter(PlaylistTrackAdapter());
  Hive.registerAdapter(LyricsLineAdapter());
  Hive.registerAdapter(PlaylistAdapter());
  Hive.registerAdapter(LikedTrackAdapter());
  Hive.registerAdapter(EmbeddedArtistAdapter());
  Hive.registerAdapter(EmbeddedAlbumAdapter());
  Hive.registerAdapter(TrackAdapter());
  Hive.registerAdapter(PlaylistTracksLengthAdapter());
  Hive.registerAdapter(FollowedArtistAdapter());
  Hive.registerAdapter(ArtistAlbumAdapter());
  Hive.registerAdapter(ArtistTopSongTrackAdapter());
  Hive.registerAdapter(ArtistAdapter());
  Hive.registerAdapter(AlbumAdapter());
  Hive.registerAdapter(AlbumTrackAdapter());
  Hive.registerAdapter(AlbumTypeAdapter());
  Hive.registerAdapter(VideoTypeAdapter());
  Hive.registerAdapter(AuthUserAdapter());
  Hive.registerAdapter(ThemeColorAdapter());
  Hive.registerAdapter(PlayabilityStatusAdapter());
  Hive.registerAdapter(HlsStreamMetadataAdapter());
  Hive.registerAdapter(LyricsAdapter());
  Hive.registerAdapter(QueueableMusicAdapter());
  Hive.registerAdapter(SyllableAdapter());
  Hive.registerAdapter(HlsStreamSourceAdapter());
  Hive.registerAdapter(AlignmentDirectionAdapter());
  Hive.registerAdapter(SavedAlbumAdapter());
  Hive.registerAdapter(LosslessAvailabilityAdapter());
}
