// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/auth.proto

package authpb

import (
	_ "github.com/Dev-Siri/wavelength/server/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOAuthRedirectUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUri   string                 `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthRedirectUrlRequest) Reset() {
	*x = GetOAuthRedirectUrlRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthRedirectUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthRedirectUrlRequest) ProtoMessage() {}

func (x *GetOAuthRedirectUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthRedirectUrlRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthRedirectUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetOAuthRedirectUrlRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type GetOAuthRedirectUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthUri      string                 `protobuf:"bytes,1,opt,name=oauth_uri,json=oauthUri,proto3" json:"oauth_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthRedirectUrlResponse) Reset() {
	*x = GetOAuthRedirectUrlResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthRedirectUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthRedirectUrlResponse) ProtoMessage() {}

func (x *GetOAuthRedirectUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthRedirectUrlResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthRedirectUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetOAuthRedirectUrlResponse) GetOauthUri() string {
	if x != nil {
		return x.OauthUri
	}
	return ""
}

type OAuthCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthCallbackRequest) Reset() {
	*x = OAuthCallbackRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthCallbackRequest) ProtoMessage() {}

func (x *OAuthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthCallbackRequest.ProtoReflect.Descriptor instead.
func (*OAuthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *OAuthCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuthCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type OAuthCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedUri     string                 `protobuf:"bytes,1,opt,name=signed_uri,json=signedUri,proto3" json:"signed_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthCallbackResponse) Reset() {
	*x = OAuthCallbackResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthCallbackResponse) ProtoMessage() {}

func (x *OAuthCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthCallbackResponse.ProtoReflect.Descriptor instead.
func (*OAuthCallbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *OAuthCallbackResponse) GetSignedUri() string {
	if x != nil {
		return x.SignedUri
	}
	return ""
}

type ConsumeAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthCode      string                 `protobuf:"bytes,1,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeAuthTokenRequest) Reset() {
	*x = ConsumeAuthTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeAuthTokenRequest) ProtoMessage() {}

func (x *ConsumeAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*ConsumeAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeAuthTokenRequest) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

type ConsumeAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeAuthTokenResponse) Reset() {
	*x = ConsumeAuthTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeAuthTokenResponse) ProtoMessage() {}

func (x *ConsumeAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*ConsumeAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeAuthTokenResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type MobileOAuthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerAuthCode string                 `protobuf:"bytes,1,opt,name=server_auth_code,json=serverAuthCode,proto3" json:"server_auth_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MobileOAuthRequest) Reset() {
	*x = MobileOAuthRequest{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileOAuthRequest) ProtoMessage() {}

func (x *MobileOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileOAuthRequest.ProtoReflect.Descriptor instead.
func (*MobileOAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *MobileOAuthRequest) GetServerAuthCode() string {
	if x != nil {
		return x.ServerAuthCode
	}
	return ""
}

type MobileOAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthCode      string                 `protobuf:"bytes,1,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobileOAuthResponse) Reset() {
	*x = MobileOAuthResponse{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileOAuthResponse) ProtoMessage() {}

func (x *MobileOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileOAuthResponse.ProtoReflect.Descriptor instead.
func (*MobileOAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *MobileOAuthResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\x1a\x12proto/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\x1aGetOAuthRedirectUrlRequest\x12!\n" +
	"\fredirect_uri\x18\x01 \x01(\tR\vredirectUri\":\n" +
	"\x1bGetOAuthRedirectUrlResponse\x12\x1b\n" +
	"\toauth_uri\x18\x01 \x01(\tR\boauthUri\"@\n" +
	"\x14OAuthCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"6\n" +
	"\x15OAuthCallbackResponse\x12\x1d\n" +
	"\n" +
	"signed_uri\x18\x01 \x01(\tR\tsignedUri\"6\n" +
	"\x17ConsumeAuthTokenRequest\x12\x1b\n" +
	"\tauth_code\x18\x01 \x01(\tR\bauthCode\"9\n" +
	"\x18ConsumeAuthTokenResponse\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\">\n" +
	"\x12MobileOAuthRequest\x12(\n" +
	"\x10server_auth_code\x18\x01 \x01(\tR\x0eserverAuthCode\"2\n" +
	"\x13MobileOAuthResponse\x12\x1b\n" +
	"\tauth_code\x18\x01 \x01(\tR\bauthCode2\xca\x02\n" +
	"\vAuthService\x12Z\n" +
	"\x13GetOAuthRedirectUrl\x12 .auth.GetOAuthRedirectUrlRequest\x1a!.auth.GetOAuthRedirectUrlResponse\x12H\n" +
	"\rOAuthCallback\x12\x1a.auth.OAuthCallbackRequest\x1a\x1b.auth.OAuthCallbackResponse\x12B\n" +
	"\vMobileOAuth\x12\x18.auth.MobileOAuthRequest\x1a\x19.auth.MobileOAuthResponse\x12Q\n" +
	"\x10ConsumeAuthToken\x12\x1d.auth.ConsumeAuthTokenRequest\x1a\x1e.auth.ConsumeAuthTokenResponseB9Z7github.com/Dev-Siri/wavelength/server/proto/auth;authpbb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_auth_proto_goTypes = []any{
	(*GetOAuthRedirectUrlRequest)(nil),  // 0: auth.GetOAuthRedirectUrlRequest
	(*GetOAuthRedirectUrlResponse)(nil), // 1: auth.GetOAuthRedirectUrlResponse
	(*OAuthCallbackRequest)(nil),        // 2: auth.OAuthCallbackRequest
	(*OAuthCallbackResponse)(nil),       // 3: auth.OAuthCallbackResponse
	(*ConsumeAuthTokenRequest)(nil),     // 4: auth.ConsumeAuthTokenRequest
	(*ConsumeAuthTokenResponse)(nil),    // 5: auth.ConsumeAuthTokenResponse
	(*MobileOAuthRequest)(nil),          // 6: auth.MobileOAuthRequest
	(*MobileOAuthResponse)(nil),         // 7: auth.MobileOAuthResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.GetOAuthRedirectUrl:input_type -> auth.GetOAuthRedirectUrlRequest
	2, // 1: auth.AuthService.OAuthCallback:input_type -> auth.OAuthCallbackRequest
	6, // 2: auth.AuthService.MobileOAuth:input_type -> auth.MobileOAuthRequest
	4, // 3: auth.AuthService.ConsumeAuthToken:input_type -> auth.ConsumeAuthTokenRequest
	1, // 4: auth.AuthService.GetOAuthRedirectUrl:output_type -> auth.GetOAuthRedirectUrlResponse
	3, // 5: auth.AuthService.OAuthCallback:output_type -> auth.OAuthCallbackResponse
	7, // 6: auth.AuthService.MobileOAuth:output_type -> auth.MobileOAuthResponse
	5, // 7: auth.AuthService.ConsumeAuthToken:output_type -> auth.ConsumeAuthTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
