// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/album.proto

package albumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	commonpb "wavelength/proto/commonpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAlbumDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       string                 `protobuf:"bytes,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumDetailsRequest) Reset() {
	*x = GetAlbumDetailsRequest{}
	mi := &file_proto_album_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumDetailsRequest) ProtoMessage() {}

func (x *GetAlbumDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{0}
}

func (x *GetAlbumDetailsRequest) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

type GetAlbumDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *commonpb.Album        `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumDetailsResponse) Reset() {
	*x = GetAlbumDetailsResponse{}
	mi := &file_proto_album_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumDetailsResponse) ProtoMessage() {}

func (x *GetAlbumDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{1}
}

func (x *GetAlbumDetailsResponse) GetAlbum() *commonpb.Album {
	if x != nil {
		return x.Album
	}
	return nil
}

type SearchAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAlbumsRequest) Reset() {
	*x = SearchAlbumsRequest{}
	mi := &file_proto_album_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlbumsRequest) ProtoMessage() {}

func (x *SearchAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlbumsRequest.ProtoReflect.Descriptor instead.
func (*SearchAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{2}
}

func (x *SearchAlbumsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchAlbumsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Albums        []*commonpb.SearchAlbum `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAlbumsResponse) Reset() {
	*x = SearchAlbumsResponse{}
	mi := &file_proto_album_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlbumsResponse) ProtoMessage() {}

func (x *SearchAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlbumsResponse.ProtoReflect.Descriptor instead.
func (*SearchAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{3}
}

func (x *SearchAlbumsResponse) GetAlbums() []*commonpb.SearchAlbum {
	if x != nil {
		return x.Albums
	}
	return nil
}

var File_proto_album_proto protoreflect.FileDescriptor

const file_proto_album_proto_rawDesc = "" +
	"\n" +
	"\x11proto/album.proto\x12\x05album\x1a\x12proto/common.proto\"3\n" +
	"\x16GetAlbumDetailsRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\tR\aalbumId\">\n" +
	"\x17GetAlbumDetailsResponse\x12#\n" +
	"\x05album\x18\x01 \x01(\v2\r.common.AlbumR\x05album\"+\n" +
	"\x13SearchAlbumsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"C\n" +
	"\x14SearchAlbumsResponse\x12+\n" +
	"\x06albums\x18\x01 \x03(\v2\x13.common.SearchAlbumR\x06albums2\xa9\x01\n" +
	"\fAlbumService\x12P\n" +
	"\x0fGetAlbumDetails\x12\x1d.album.GetAlbumDetailsRequest\x1a\x1e.album.GetAlbumDetailsResponse\x12G\n" +
	"\fSearchAlbums\x12\x1a.album.SearchAlbumsRequest\x1a\x1b.album.SearchAlbumsResponseB'Z%wavelength/server/proto/album;albumpbb\x06proto3"

var (
	file_proto_album_proto_rawDescOnce sync.Once
	file_proto_album_proto_rawDescData []byte
)

func file_proto_album_proto_rawDescGZIP() []byte {
	file_proto_album_proto_rawDescOnce.Do(func() {
		file_proto_album_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_album_proto_rawDesc), len(file_proto_album_proto_rawDesc)))
	})
	return file_proto_album_proto_rawDescData
}

var file_proto_album_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_album_proto_goTypes = []any{
	(*GetAlbumDetailsRequest)(nil),  // 0: album.GetAlbumDetailsRequest
	(*GetAlbumDetailsResponse)(nil), // 1: album.GetAlbumDetailsResponse
	(*SearchAlbumsRequest)(nil),     // 2: album.SearchAlbumsRequest
	(*SearchAlbumsResponse)(nil),    // 3: album.SearchAlbumsResponse
	(*commonpb.Album)(nil),          // 4: common.Album
	(*commonpb.SearchAlbum)(nil),    // 5: common.SearchAlbum
}
var file_proto_album_proto_depIdxs = []int32{
	4, // 0: album.GetAlbumDetailsResponse.album:type_name -> common.Album
	5, // 1: album.SearchAlbumsResponse.albums:type_name -> common.SearchAlbum
	0, // 2: album.AlbumService.GetAlbumDetails:input_type -> album.GetAlbumDetailsRequest
	2, // 3: album.AlbumService.SearchAlbums:input_type -> album.SearchAlbumsRequest
	1, // 4: album.AlbumService.GetAlbumDetails:output_type -> album.GetAlbumDetailsResponse
	3, // 5: album.AlbumService.SearchAlbums:output_type -> album.SearchAlbumsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_album_proto_init() }
func file_proto_album_proto_init() {
	if File_proto_album_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_album_proto_rawDesc), len(file_proto_album_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_album_proto_goTypes,
		DependencyIndexes: file_proto_album_proto_depIdxs,
		MessageInfos:      file_proto_album_proto_msgTypes,
	}.Build()
	File_proto_album_proto = out.File
	file_proto_album_proto_goTypes = nil
	file_proto_album_proto_depIdxs = nil
}
