// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/album.proto

package albumpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlbumService_GetAlbumDetails_FullMethodName   = "/album.AlbumService/GetAlbumDetails"
	AlbumService_SearchAlbums_FullMethodName      = "/album.AlbumService/SearchAlbums"
	AlbumService_CreateTrackAlbum_FullMethodName  = "/album.AlbumService/CreateTrackAlbum"
	AlbumService_GetAlbumLiveCover_FullMethodName = "/album.AlbumService/GetAlbumLiveCover"
	AlbumService_IsAlbumLossless_FullMethodName   = "/album.AlbumService/IsAlbumLossless"
	AlbumService_IsAlbumSaved_FullMethodName      = "/album.AlbumService/IsAlbumSaved"
	AlbumService_SaveAlbum_FullMethodName         = "/album.AlbumService/SaveAlbum"
	AlbumService_GetSavedAlbums_FullMethodName    = "/album.AlbumService/GetSavedAlbums"
)

// AlbumServiceClient is the client API for AlbumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlbumServiceClient interface {
	GetAlbumDetails(ctx context.Context, in *GetAlbumDetailsRequest, opts ...grpc.CallOption) (*GetAlbumDetailsResponse, error)
	SearchAlbums(ctx context.Context, in *SearchAlbumsRequest, opts ...grpc.CallOption) (*SearchAlbumsResponse, error)
	CreateTrackAlbum(ctx context.Context, in *CreateTrackAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAlbumLiveCover(ctx context.Context, in *GetAlbumLiveCoverRequest, opts ...grpc.CallOption) (*GetAlbumLiveCoverResponse, error)
	IsAlbumLossless(ctx context.Context, in *IsAlbumLosslessRequest, opts ...grpc.CallOption) (*IsAlbumLosslessResponse, error)
	IsAlbumSaved(ctx context.Context, in *IsAlbumSavedRequest, opts ...grpc.CallOption) (*IsAlbumSavedResponse, error)
	SaveAlbum(ctx context.Context, in *SaveAlbumRequest, opts ...grpc.CallOption) (*SaveAlbumResponse, error)
	GetSavedAlbums(ctx context.Context, in *GetSavedAlbumsRequest, opts ...grpc.CallOption) (*GetSavedAlbumsResponse, error)
}

type albumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlbumServiceClient(cc grpc.ClientConnInterface) AlbumServiceClient {
	return &albumServiceClient{cc}
}

func (c *albumServiceClient) GetAlbumDetails(ctx context.Context, in *GetAlbumDetailsRequest, opts ...grpc.CallOption) (*GetAlbumDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlbumDetailsResponse)
	err := c.cc.Invoke(ctx, AlbumService_GetAlbumDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) SearchAlbums(ctx context.Context, in *SearchAlbumsRequest, opts ...grpc.CallOption) (*SearchAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAlbumsResponse)
	err := c.cc.Invoke(ctx, AlbumService_SearchAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) CreateTrackAlbum(ctx context.Context, in *CreateTrackAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlbumService_CreateTrackAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) GetAlbumLiveCover(ctx context.Context, in *GetAlbumLiveCoverRequest, opts ...grpc.CallOption) (*GetAlbumLiveCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlbumLiveCoverResponse)
	err := c.cc.Invoke(ctx, AlbumService_GetAlbumLiveCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) IsAlbumLossless(ctx context.Context, in *IsAlbumLosslessRequest, opts ...grpc.CallOption) (*IsAlbumLosslessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAlbumLosslessResponse)
	err := c.cc.Invoke(ctx, AlbumService_IsAlbumLossless_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) IsAlbumSaved(ctx context.Context, in *IsAlbumSavedRequest, opts ...grpc.CallOption) (*IsAlbumSavedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAlbumSavedResponse)
	err := c.cc.Invoke(ctx, AlbumService_IsAlbumSaved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) SaveAlbum(ctx context.Context, in *SaveAlbumRequest, opts ...grpc.CallOption) (*SaveAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAlbumResponse)
	err := c.cc.Invoke(ctx, AlbumService_SaveAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) GetSavedAlbums(ctx context.Context, in *GetSavedAlbumsRequest, opts ...grpc.CallOption) (*GetSavedAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSavedAlbumsResponse)
	err := c.cc.Invoke(ctx, AlbumService_GetSavedAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbumServiceServer is the server API for AlbumService service.
// All implementations must embed UnimplementedAlbumServiceServer
// for forward compatibility.
type AlbumServiceServer interface {
	GetAlbumDetails(context.Context, *GetAlbumDetailsRequest) (*GetAlbumDetailsResponse, error)
	SearchAlbums(context.Context, *SearchAlbumsRequest) (*SearchAlbumsResponse, error)
	CreateTrackAlbum(context.Context, *CreateTrackAlbumRequest) (*emptypb.Empty, error)
	GetAlbumLiveCover(context.Context, *GetAlbumLiveCoverRequest) (*GetAlbumLiveCoverResponse, error)
	IsAlbumLossless(context.Context, *IsAlbumLosslessRequest) (*IsAlbumLosslessResponse, error)
	IsAlbumSaved(context.Context, *IsAlbumSavedRequest) (*IsAlbumSavedResponse, error)
	SaveAlbum(context.Context, *SaveAlbumRequest) (*SaveAlbumResponse, error)
	GetSavedAlbums(context.Context, *GetSavedAlbumsRequest) (*GetSavedAlbumsResponse, error)
	mustEmbedUnimplementedAlbumServiceServer()
}

// UnimplementedAlbumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlbumServiceServer struct{}

func (UnimplementedAlbumServiceServer) GetAlbumDetails(context.Context, *GetAlbumDetailsRequest) (*GetAlbumDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbumDetails not implemented")
}
func (UnimplementedAlbumServiceServer) SearchAlbums(context.Context, *SearchAlbumsRequest) (*SearchAlbumsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAlbums not implemented")
}
func (UnimplementedAlbumServiceServer) CreateTrackAlbum(context.Context, *CreateTrackAlbumRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrackAlbum not implemented")
}
func (UnimplementedAlbumServiceServer) GetAlbumLiveCover(context.Context, *GetAlbumLiveCoverRequest) (*GetAlbumLiveCoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbumLiveCover not implemented")
}
func (UnimplementedAlbumServiceServer) IsAlbumLossless(context.Context, *IsAlbumLosslessRequest) (*IsAlbumLosslessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAlbumLossless not implemented")
}
func (UnimplementedAlbumServiceServer) IsAlbumSaved(context.Context, *IsAlbumSavedRequest) (*IsAlbumSavedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAlbumSaved not implemented")
}
func (UnimplementedAlbumServiceServer) SaveAlbum(context.Context, *SaveAlbumRequest) (*SaveAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAlbum not implemented")
}
func (UnimplementedAlbumServiceServer) GetSavedAlbums(context.Context, *GetSavedAlbumsRequest) (*GetSavedAlbumsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSavedAlbums not implemented")
}
func (UnimplementedAlbumServiceServer) mustEmbedUnimplementedAlbumServiceServer() {}
func (UnimplementedAlbumServiceServer) testEmbeddedByValue()                      {}

// UnsafeAlbumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlbumServiceServer will
// result in compilation errors.
type UnsafeAlbumServiceServer interface {
	mustEmbedUnimplementedAlbumServiceServer()
}

func RegisterAlbumServiceServer(s grpc.ServiceRegistrar, srv AlbumServiceServer) {
	// If the following call panics, it indicates UnimplementedAlbumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlbumService_ServiceDesc, srv)
}

func _AlbumService_GetAlbumDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).GetAlbumDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_GetAlbumDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).GetAlbumDetails(ctx, req.(*GetAlbumDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_SearchAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).SearchAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_SearchAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).SearchAlbums(ctx, req.(*SearchAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_CreateTrackAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).CreateTrackAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_CreateTrackAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).CreateTrackAlbum(ctx, req.(*CreateTrackAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_GetAlbumLiveCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumLiveCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).GetAlbumLiveCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_GetAlbumLiveCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).GetAlbumLiveCover(ctx, req.(*GetAlbumLiveCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_IsAlbumLossless_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAlbumLosslessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).IsAlbumLossless(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_IsAlbumLossless_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).IsAlbumLossless(ctx, req.(*IsAlbumLosslessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_IsAlbumSaved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAlbumSavedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).IsAlbumSaved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_IsAlbumSaved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).IsAlbumSaved(ctx, req.(*IsAlbumSavedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_SaveAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).SaveAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_SaveAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).SaveAlbum(ctx, req.(*SaveAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_GetSavedAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).GetSavedAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumService_GetSavedAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).GetSavedAlbums(ctx, req.(*GetSavedAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlbumService_ServiceDesc is the grpc.ServiceDesc for AlbumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlbumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "album.AlbumService",
	HandlerType: (*AlbumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlbumDetails",
			Handler:    _AlbumService_GetAlbumDetails_Handler,
		},
		{
			MethodName: "SearchAlbums",
			Handler:    _AlbumService_SearchAlbums_Handler,
		},
		{
			MethodName: "CreateTrackAlbum",
			Handler:    _AlbumService_CreateTrackAlbum_Handler,
		},
		{
			MethodName: "GetAlbumLiveCover",
			Handler:    _AlbumService_GetAlbumLiveCover_Handler,
		},
		{
			MethodName: "IsAlbumLossless",
			Handler:    _AlbumService_IsAlbumLossless_Handler,
		},
		{
			MethodName: "IsAlbumSaved",
			Handler:    _AlbumService_IsAlbumSaved_Handler,
		},
		{
			MethodName: "SaveAlbum",
			Handler:    _AlbumService_SaveAlbum_Handler,
		},
		{
			MethodName: "GetSavedAlbums",
			Handler:    _AlbumService_GetSavedAlbums_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/album.proto",
}
