// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/image.proto

package imagepb

import (
	commonpb "github.com/Dev-Siri/wavelength/server/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetThemeColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThemeColorRequest) Reset() {
	*x = GetThemeColorRequest{}
	mi := &file_proto_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThemeColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThemeColorRequest) ProtoMessage() {}

func (x *GetThemeColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThemeColorRequest.ProtoReflect.Descriptor instead.
func (*GetThemeColorRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{0}
}

func (x *GetThemeColorRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetThemeColorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThemeColor    *commonpb.ThemeColor   `protobuf:"bytes,1,opt,name=theme_color,json=themeColor,proto3" json:"theme_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThemeColorResponse) Reset() {
	*x = GetThemeColorResponse{}
	mi := &file_proto_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThemeColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThemeColorResponse) ProtoMessage() {}

func (x *GetThemeColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThemeColorResponse.ProtoReflect.Descriptor instead.
func (*GetThemeColorResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{1}
}

func (x *GetThemeColorResponse) GetThemeColor() *commonpb.ThemeColor {
	if x != nil {
		return x.ThemeColor
	}
	return nil
}

type ResizeImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeImageRequest) Reset() {
	*x = ResizeImageRequest{}
	mi := &file_proto_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeImageRequest) ProtoMessage() {}

func (x *ResizeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeImageRequest.ProtoReflect.Descriptor instead.
func (*ResizeImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{2}
}

func (x *ResizeImageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ResizeImageRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResizeImageRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type ResizeImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeImageResponse) Reset() {
	*x = ResizeImageResponse{}
	mi := &file_proto_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeImageResponse) ProtoMessage() {}

func (x *ResizeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeImageResponse.ProtoReflect.Descriptor instead.
func (*ResizeImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{3}
}

func (x *ResizeImageResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ResizeImageResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetCoverEffectColorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoverEffectColorsRequest) Reset() {
	*x = GetCoverEffectColorsRequest{}
	mi := &file_proto_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoverEffectColorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoverEffectColorsRequest) ProtoMessage() {}

func (x *GetCoverEffectColorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoverEffectColorsRequest.ProtoReflect.Descriptor instead.
func (*GetCoverEffectColorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoverEffectColorsRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetCoverEffectColorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Colors        []*commonpb.ThemeColor `protobuf:"bytes,1,rep,name=colors,proto3" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoverEffectColorsResponse) Reset() {
	*x = GetCoverEffectColorsResponse{}
	mi := &file_proto_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoverEffectColorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoverEffectColorsResponse) ProtoMessage() {}

func (x *GetCoverEffectColorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoverEffectColorsResponse.ProtoReflect.Descriptor instead.
func (*GetCoverEffectColorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{5}
}

func (x *GetCoverEffectColorsResponse) GetColors() []*commonpb.ThemeColor {
	if x != nil {
		return x.Colors
	}
	return nil
}

var File_proto_image_proto protoreflect.FileDescriptor

const file_proto_image_proto_rawDesc = "" +
	"\n" +
	"\x11proto/image.proto\x12\x05image\x1a\x12proto/common.proto\"3\n" +
	"\x14GetThemeColorRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\"L\n" +
	"\x15GetThemeColorResponse\x123\n" +
	"\vtheme_color\x18\x01 \x01(\v2\x12.common.ThemeColorR\n" +
	"themeColor\"_\n" +
	"\x12ResizeImageRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\"Q\n" +
	"\x13ResizeImageResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\":\n" +
	"\x1bGetCoverEffectColorsRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\"J\n" +
	"\x1cGetCoverEffectColorsResponse\x12*\n" +
	"\x06colors\x18\x01 \x03(\v2\x12.common.ThemeColorR\x06colors2\x81\x02\n" +
	"\fImageService\x12J\n" +
	"\rGetThemeColor\x12\x1b.image.GetThemeColorRequest\x1a\x1c.image.GetThemeColorResponse\x12D\n" +
	"\vResizeImage\x12\x19.image.ResizeImageRequest\x1a\x1a.image.ResizeImageResponse\x12_\n" +
	"\x14GetCoverEffectColors\x12\".image.GetCoverEffectColorsRequest\x1a#.image.GetCoverEffectColorsResponseB;Z9github.com/Dev-Siri/wavelength/server/proto/image;imagepbb\x06proto3"

var (
	file_proto_image_proto_rawDescOnce sync.Once
	file_proto_image_proto_rawDescData []byte
)

func file_proto_image_proto_rawDescGZIP() []byte {
	file_proto_image_proto_rawDescOnce.Do(func() {
		file_proto_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_proto_rawDesc), len(file_proto_image_proto_rawDesc)))
	})
	return file_proto_image_proto_rawDescData
}

var file_proto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_image_proto_goTypes = []any{
	(*GetThemeColorRequest)(nil),         // 0: image.GetThemeColorRequest
	(*GetThemeColorResponse)(nil),        // 1: image.GetThemeColorResponse
	(*ResizeImageRequest)(nil),           // 2: image.ResizeImageRequest
	(*ResizeImageResponse)(nil),          // 3: image.ResizeImageResponse
	(*GetCoverEffectColorsRequest)(nil),  // 4: image.GetCoverEffectColorsRequest
	(*GetCoverEffectColorsResponse)(nil), // 5: image.GetCoverEffectColorsResponse
	(*commonpb.ThemeColor)(nil),          // 6: common.ThemeColor
}
var file_proto_image_proto_depIdxs = []int32{
	6, // 0: image.GetThemeColorResponse.theme_color:type_name -> common.ThemeColor
	6, // 1: image.GetCoverEffectColorsResponse.colors:type_name -> common.ThemeColor
	0, // 2: image.ImageService.GetThemeColor:input_type -> image.GetThemeColorRequest
	2, // 3: image.ImageService.ResizeImage:input_type -> image.ResizeImageRequest
	4, // 4: image.ImageService.GetCoverEffectColors:input_type -> image.GetCoverEffectColorsRequest
	1, // 5: image.ImageService.GetThemeColor:output_type -> image.GetThemeColorResponse
	3, // 6: image.ImageService.ResizeImage:output_type -> image.ResizeImageResponse
	5, // 7: image.ImageService.GetCoverEffectColors:output_type -> image.GetCoverEffectColorsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_image_proto_init() }
func file_proto_image_proto_init() {
	if File_proto_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_proto_rawDesc), len(file_proto_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_proto_goTypes,
		DependencyIndexes: file_proto_image_proto_depIdxs,
		MessageInfos:      file_proto_image_proto_msgTypes,
	}.Build()
	File_proto_image_proto = out.File
	file_proto_image_proto_goTypes = nil
	file_proto_image_proto_depIdxs = nil
}
