// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/collector.proto

package collectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectYouTubeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectYouTubeStreamRequest) Reset() {
	*x = CollectYouTubeStreamRequest{}
	mi := &file_proto_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectYouTubeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectYouTubeStreamRequest) ProtoMessage() {}

func (x *CollectYouTubeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectYouTubeStreamRequest.ProtoReflect.Descriptor instead.
func (*CollectYouTubeStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{0}
}

func (x *CollectYouTubeStreamRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type CollectHifiStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectHifiStreamRequest) Reset() {
	*x = CollectHifiStreamRequest{}
	mi := &file_proto_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectHifiStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectHifiStreamRequest) ProtoMessage() {}

func (x *CollectHifiStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectHifiStreamRequest.ProtoReflect.Descriptor instead.
func (*CollectHifiStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *CollectHifiStreamRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

var File_proto_collector_proto protoreflect.FileDescriptor

const file_proto_collector_proto_rawDesc = "" +
	"\n" +
	"\x15proto/collector.proto\x12\tcollector\x1a\x1bgoogle/protobuf/empty.proto\"8\n" +
	"\x1bCollectYouTubeStreamRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"5\n" +
	"\x18CollectHifiStreamRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId2\xbc\x01\n" +
	"\x10CollectorService\x12V\n" +
	"\x14CollectYouTubeStream\x12&.collector.CollectYouTubeStreamRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11CollectHifiStream\x12#.collector.CollectHifiStreamRequest\x1a\x16.google.protobuf.EmptyBCZAgithub.com/Dev-Siri/wavelength/server/proto/collector;collectorpbb\x06proto3"

var (
	file_proto_collector_proto_rawDescOnce sync.Once
	file_proto_collector_proto_rawDescData []byte
)

func file_proto_collector_proto_rawDescGZIP() []byte {
	file_proto_collector_proto_rawDescOnce.Do(func() {
		file_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collector_proto_rawDesc), len(file_proto_collector_proto_rawDesc)))
	})
	return file_proto_collector_proto_rawDescData
}

var file_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_collector_proto_goTypes = []any{
	(*CollectYouTubeStreamRequest)(nil), // 0: collector.CollectYouTubeStreamRequest
	(*CollectHifiStreamRequest)(nil),    // 1: collector.CollectHifiStreamRequest
	(*emptypb.Empty)(nil),               // 2: google.protobuf.Empty
}
var file_proto_collector_proto_depIdxs = []int32{
	0, // 0: collector.CollectorService.CollectYouTubeStream:input_type -> collector.CollectYouTubeStreamRequest
	1, // 1: collector.CollectorService.CollectHifiStream:input_type -> collector.CollectHifiStreamRequest
	2, // 2: collector.CollectorService.CollectYouTubeStream:output_type -> google.protobuf.Empty
	2, // 3: collector.CollectorService.CollectHifiStream:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_collector_proto_init() }
func file_proto_collector_proto_init() {
	if File_proto_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collector_proto_rawDesc), len(file_proto_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collector_proto_goTypes,
		DependencyIndexes: file_proto_collector_proto_depIdxs,
		MessageInfos:      file_proto_collector_proto_msgTypes,
	}.Build()
	File_proto_collector_proto = out.File
	file_proto_collector_proto_goTypes = nil
	file_proto_collector_proto_depIdxs = nil
}
