import * as grpc from "@grpc/grpc-js";
import { YTNodes } from "youtubei.js";

import type { Album, AlbumTrack, EmbeddedArtist } from "@/gen/proto/common.js";
import type {
  GetAlbumDetailsRequest,
  GetAlbumDetailsResponse,
} from "@/gen/proto/yt_scraper.js";

import { getYtMusicClient } from "@/innertube.js";
import { createErrorResponse } from "@/response.js";
import { parseStringToAlbumType } from "@/utils/parse.js";
import { getHighestQualityThumbnail } from "@/utils/thumbnail.js";

export default async function getAlbumDetails(
  call: grpc.ServerUnaryCall<GetAlbumDetailsRequest, GetAlbumDetailsResponse>,
  callback: grpc.sendUnaryData<GetAlbumDetailsResponse>,
) {
  try {
    const music = await getYtMusicClient();
    const { header, contents } = await music.getAlbum(call.request.albumId);

    if (!header || !contents)
      return callback(
        createErrorResponse("YouTube Music sent an empty response."),
      );

    const musicResponseHeader = header.as(YTNodes.MusicResponsiveHeader);

    // YouTube tracks in albums are actually OMV (Official Music Video) tracks and not
    // audio-only sources which contain the actual useful metadata. So instead of fetching album tracks,
    // we get the playlistId from this deeply nested object of the first track (always present in Single/EP/Album),
    // and use that to request the playlist version of the album instead which has tracks pointing to
    // official audio-only tracks auto-generated by YouTube to keep the content clean from otherwise
    // what we'd get in albums as basically YouTube videos.
    const albumPlaylistId =
      contents[0]?.flex_columns[0]?.title.endpoint?.payload.playlistId;

    if (!albumPlaylistId)
      return callback(
        createErrorResponse("YouTube Music album's playlist does not exist."),
      );

    const albumPlaylist = await music.getPlaylist(albumPlaylistId);

    if (
      !musicResponseHeader.subtitle.text ||
      !musicResponseHeader.second_subtitle.text ||
      !musicResponseHeader.title.text ||
      !musicResponseHeader.subtitle.text ||
      !musicResponseHeader.strapline_text_one.text
    )
      return callback(
        createErrorResponse("YouTube Music sent an empty response."),
      );

    const musicList = contents.as(YTNodes.MusicResponsiveListItem);

    if (!musicResponseHeader.thumbnail) return;

    const thumbnail = getHighestQualityThumbnail(musicResponseHeader.thumbnail);
    if (!thumbnail) {
      const status = new grpc.StatusBuilder()
        .withCode(grpc.status.INTERNAL)
        .withDetails("YouTube Music sent an invalid response.")
        .build();
      return callback(status);
    }

    const [albumType, release] = musicResponseHeader.subtitle.text.split(" • ");
    if (!albumType || !release) {
      const status = new grpc.StatusBuilder()
        .withCode(grpc.status.INTERNAL)
        .withDetails("YouTube Music sent an invalid response.")
        .build();
      return callback(status);
    }

    const [, totalDuration] =
      musicResponseHeader.second_subtitle.text.split("•");
    if (!totalDuration) {
      const status = new grpc.StatusBuilder()
        .withCode(grpc.status.INTERNAL)
        .withDetails("YouTube Music sent an invalid response.")
        .build();
      return callback(status);
    }

    const playlistAlbumTracksRaw = albumPlaylist.contents ?? [];

    const albumTracks: AlbumTrack[] = [];
    for (let i = 0; i < playlistAlbumTracksRaw.length; i++) {
      const track = playlistAlbumTracksRaw[i]?.as(
        YTNodes.MusicResponsiveListItem,
      );
      if (!track || !track.title || !track.duration || !track.id) continue;

      const positionInArray = i + 1;
      const artistFieldToSearch = track.authors || track.artists;
      const parsedArtistsField: EmbeddedArtist[] =
        artistFieldToSearch?.map((artist) => ({
          title: artist.name,
          browseId: artist.channel_id ?? "VARIOUS_ARTISTS",
        })) ?? [];

      const artists = parsedArtistsField.length
        ? parsedArtistsField
        : [
            {
              title:
                track.flex_columns[1]?.as(
                  YTNodes.MusicResponsiveListItemFlexColumn,
                ).title.text ?? "VARIOUS_ARTISTS",
              browseId: "VARIOUS_ARTISTS",
            },
          ];

      const isExplicit = !!track?.badges?.some(
        (badge) =>
          badge.as(YTNodes.MusicInlineBadge).icon_type ===
          "MUSIC_EXPLICIT_BADGE",
      );

      const albumTrack = {
        title: track.title,
        positionInAlbum: Number(track.index?.text ?? positionInArray),
        duration: track.duration.seconds,
        videoId: track.id,
        isExplicit,
        artists,
      } satisfies AlbumTrack;

      albumTracks.push(albumTrack);
    }

    const album = {
      title: musicResponseHeader.title.text,
      description: musicResponseHeader.description?.description?.text ?? "",
      cover: thumbnail.url,
      albumType: parseStringToAlbumType(albumType),
      release,
      totalDuration: totalDuration.trim(),
      artist: {
        title: musicResponseHeader.strapline_text_one.text,
        browseId:
          musicResponseHeader.strapline_text_one.endpoint?.payload.browseId ??
          "VARIOUS_ARTISTS",
      },
      totalSongCount: albumTracks.length,
      albumTracks,
    } satisfies Album;

    return callback(null, { album });
  } catch (error) {
    console.error("Album details fetch failed.", error);
    callback(createErrorResponse(`Album details fetch failed: ${error}`));
  }
}
