// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/music.proto

package musicpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MusicService_LikeTrack_FullMethodName                 = "/music.MusicService/LikeTrack"
	MusicService_IsTrackLiked_FullMethodName              = "/music.MusicService/IsTrackLiked"
	MusicService_GetLikedTrackCount_FullMethodName        = "/music.MusicService/GetLikedTrackCount"
	MusicService_GetLikedTracksLength_FullMethodName      = "/music.MusicService/GetLikedTracksLength"
	MusicService_GetLikedTracks_FullMethodName            = "/music.MusicService/GetLikedTracks"
	MusicService_GetMusicSearchSuggestions_FullMethodName = "/music.MusicService/GetMusicSearchSuggestions"
	MusicService_GetQuickPicks_FullMethodName             = "/music.MusicService/GetQuickPicks"
	MusicService_GetMusicDuration_FullMethodName          = "/music.MusicService/GetMusicDuration"
	MusicService_GetMusicTrackStats_FullMethodName        = "/music.MusicService/GetMusicTrackStats"
)

// MusicServiceClient is the client API for MusicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MusicServiceClient interface {
	LikeTrack(ctx context.Context, in *LikeTrackRequest, opts ...grpc.CallOption) (*LikeTrackResponse, error)
	IsTrackLiked(ctx context.Context, in *IsTrackLikedRequest, opts ...grpc.CallOption) (*IsTrackLikedResponse, error)
	GetLikedTrackCount(ctx context.Context, in *GetLikedTrackCountRequest, opts ...grpc.CallOption) (*GetLikedTrackCountResponse, error)
	GetLikedTracksLength(ctx context.Context, in *GetLikedTracksLengthRequest, opts ...grpc.CallOption) (*GetLikedTracksLengthResponse, error)
	GetLikedTracks(ctx context.Context, in *GetLikedTracksRequest, opts ...grpc.CallOption) (*GetLikedTracksResponse, error)
	GetMusicSearchSuggestions(ctx context.Context, in *GetMusicSearchSuggestionsRequest, opts ...grpc.CallOption) (*GetMusicSearchSuggestionsResponse, error)
	GetQuickPicks(ctx context.Context, in *GetQuickPicksRequest, opts ...grpc.CallOption) (*GetQuickPicksResponse, error)
	GetMusicDuration(ctx context.Context, in *GetMusicDurationRequest, opts ...grpc.CallOption) (*GetMusicDurationResponse, error)
	GetMusicTrackStats(ctx context.Context, in *GetMusicTrackStatsRequest, opts ...grpc.CallOption) (*GetMusicTrackStatsResponse, error)
}

type musicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMusicServiceClient(cc grpc.ClientConnInterface) MusicServiceClient {
	return &musicServiceClient{cc}
}

func (c *musicServiceClient) LikeTrack(ctx context.Context, in *LikeTrackRequest, opts ...grpc.CallOption) (*LikeTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeTrackResponse)
	err := c.cc.Invoke(ctx, MusicService_LikeTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) IsTrackLiked(ctx context.Context, in *IsTrackLikedRequest, opts ...grpc.CallOption) (*IsTrackLikedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsTrackLikedResponse)
	err := c.cc.Invoke(ctx, MusicService_IsTrackLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetLikedTrackCount(ctx context.Context, in *GetLikedTrackCountRequest, opts ...grpc.CallOption) (*GetLikedTrackCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikedTrackCountResponse)
	err := c.cc.Invoke(ctx, MusicService_GetLikedTrackCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetLikedTracksLength(ctx context.Context, in *GetLikedTracksLengthRequest, opts ...grpc.CallOption) (*GetLikedTracksLengthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikedTracksLengthResponse)
	err := c.cc.Invoke(ctx, MusicService_GetLikedTracksLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetLikedTracks(ctx context.Context, in *GetLikedTracksRequest, opts ...grpc.CallOption) (*GetLikedTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikedTracksResponse)
	err := c.cc.Invoke(ctx, MusicService_GetLikedTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetMusicSearchSuggestions(ctx context.Context, in *GetMusicSearchSuggestionsRequest, opts ...grpc.CallOption) (*GetMusicSearchSuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMusicSearchSuggestionsResponse)
	err := c.cc.Invoke(ctx, MusicService_GetMusicSearchSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetQuickPicks(ctx context.Context, in *GetQuickPicksRequest, opts ...grpc.CallOption) (*GetQuickPicksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuickPicksResponse)
	err := c.cc.Invoke(ctx, MusicService_GetQuickPicks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetMusicDuration(ctx context.Context, in *GetMusicDurationRequest, opts ...grpc.CallOption) (*GetMusicDurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMusicDurationResponse)
	err := c.cc.Invoke(ctx, MusicService_GetMusicDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetMusicTrackStats(ctx context.Context, in *GetMusicTrackStatsRequest, opts ...grpc.CallOption) (*GetMusicTrackStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMusicTrackStatsResponse)
	err := c.cc.Invoke(ctx, MusicService_GetMusicTrackStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MusicServiceServer is the server API for MusicService service.
// All implementations must embed UnimplementedMusicServiceServer
// for forward compatibility.
type MusicServiceServer interface {
	LikeTrack(context.Context, *LikeTrackRequest) (*LikeTrackResponse, error)
	IsTrackLiked(context.Context, *IsTrackLikedRequest) (*IsTrackLikedResponse, error)
	GetLikedTrackCount(context.Context, *GetLikedTrackCountRequest) (*GetLikedTrackCountResponse, error)
	GetLikedTracksLength(context.Context, *GetLikedTracksLengthRequest) (*GetLikedTracksLengthResponse, error)
	GetLikedTracks(context.Context, *GetLikedTracksRequest) (*GetLikedTracksResponse, error)
	GetMusicSearchSuggestions(context.Context, *GetMusicSearchSuggestionsRequest) (*GetMusicSearchSuggestionsResponse, error)
	GetQuickPicks(context.Context, *GetQuickPicksRequest) (*GetQuickPicksResponse, error)
	GetMusicDuration(context.Context, *GetMusicDurationRequest) (*GetMusicDurationResponse, error)
	GetMusicTrackStats(context.Context, *GetMusicTrackStatsRequest) (*GetMusicTrackStatsResponse, error)
	mustEmbedUnimplementedMusicServiceServer()
}

// UnimplementedMusicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMusicServiceServer struct{}

func (UnimplementedMusicServiceServer) LikeTrack(context.Context, *LikeTrackRequest) (*LikeTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeTrack not implemented")
}
func (UnimplementedMusicServiceServer) IsTrackLiked(context.Context, *IsTrackLikedRequest) (*IsTrackLikedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsTrackLiked not implemented")
}
func (UnimplementedMusicServiceServer) GetLikedTrackCount(context.Context, *GetLikedTrackCountRequest) (*GetLikedTrackCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikedTrackCount not implemented")
}
func (UnimplementedMusicServiceServer) GetLikedTracksLength(context.Context, *GetLikedTracksLengthRequest) (*GetLikedTracksLengthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikedTracksLength not implemented")
}
func (UnimplementedMusicServiceServer) GetLikedTracks(context.Context, *GetLikedTracksRequest) (*GetLikedTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikedTracks not implemented")
}
func (UnimplementedMusicServiceServer) GetMusicSearchSuggestions(context.Context, *GetMusicSearchSuggestionsRequest) (*GetMusicSearchSuggestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMusicSearchSuggestions not implemented")
}
func (UnimplementedMusicServiceServer) GetQuickPicks(context.Context, *GetQuickPicksRequest) (*GetQuickPicksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuickPicks not implemented")
}
func (UnimplementedMusicServiceServer) GetMusicDuration(context.Context, *GetMusicDurationRequest) (*GetMusicDurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMusicDuration not implemented")
}
func (UnimplementedMusicServiceServer) GetMusicTrackStats(context.Context, *GetMusicTrackStatsRequest) (*GetMusicTrackStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMusicTrackStats not implemented")
}
func (UnimplementedMusicServiceServer) mustEmbedUnimplementedMusicServiceServer() {}
func (UnimplementedMusicServiceServer) testEmbeddedByValue()                      {}

// UnsafeMusicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MusicServiceServer will
// result in compilation errors.
type UnsafeMusicServiceServer interface {
	mustEmbedUnimplementedMusicServiceServer()
}

func RegisterMusicServiceServer(s grpc.ServiceRegistrar, srv MusicServiceServer) {
	// If the following call panics, it indicates UnimplementedMusicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MusicService_ServiceDesc, srv)
}

func _MusicService_LikeTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).LikeTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_LikeTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).LikeTrack(ctx, req.(*LikeTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_IsTrackLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsTrackLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).IsTrackLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_IsTrackLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).IsTrackLiked(ctx, req.(*IsTrackLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetLikedTrackCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedTrackCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetLikedTrackCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetLikedTrackCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetLikedTrackCount(ctx, req.(*GetLikedTrackCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetLikedTracksLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedTracksLengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetLikedTracksLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetLikedTracksLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetLikedTracksLength(ctx, req.(*GetLikedTracksLengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetLikedTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetLikedTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetLikedTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetLikedTracks(ctx, req.(*GetLikedTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetMusicSearchSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMusicSearchSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetMusicSearchSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetMusicSearchSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetMusicSearchSuggestions(ctx, req.(*GetMusicSearchSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetQuickPicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuickPicksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetQuickPicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetQuickPicks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetQuickPicks(ctx, req.(*GetQuickPicksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetMusicDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMusicDurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetMusicDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetMusicDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetMusicDuration(ctx, req.(*GetMusicDurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetMusicTrackStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMusicTrackStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetMusicTrackStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicService_GetMusicTrackStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetMusicTrackStats(ctx, req.(*GetMusicTrackStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MusicService_ServiceDesc is the grpc.ServiceDesc for MusicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MusicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "music.MusicService",
	HandlerType: (*MusicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeTrack",
			Handler:    _MusicService_LikeTrack_Handler,
		},
		{
			MethodName: "IsTrackLiked",
			Handler:    _MusicService_IsTrackLiked_Handler,
		},
		{
			MethodName: "GetLikedTrackCount",
			Handler:    _MusicService_GetLikedTrackCount_Handler,
		},
		{
			MethodName: "GetLikedTracksLength",
			Handler:    _MusicService_GetLikedTracksLength_Handler,
		},
		{
			MethodName: "GetLikedTracks",
			Handler:    _MusicService_GetLikedTracks_Handler,
		},
		{
			MethodName: "GetMusicSearchSuggestions",
			Handler:    _MusicService_GetMusicSearchSuggestions_Handler,
		},
		{
			MethodName: "GetQuickPicks",
			Handler:    _MusicService_GetQuickPicks_Handler,
		},
		{
			MethodName: "GetMusicDuration",
			Handler:    _MusicService_GetMusicDuration_Handler,
		},
		{
			MethodName: "GetMusicTrackStats",
			Handler:    _MusicService_GetMusicTrackStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/music.proto",
}
