// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/artist.proto

package artistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtistService_GetFollowedArtists_FullMethodName        = "/artist.ArtistService/GetFollowedArtists"
	ArtistService_GetArtistDetails_FullMethodName          = "/artist.ArtistService/GetArtistDetails"
	ArtistService_SearchArtists_FullMethodName             = "/artist.ArtistService/SearchArtists"
	ArtistService_FollowArtist_FullMethodName              = "/artist.ArtistService/FollowArtist"
	ArtistService_IsFollowingArtist_FullMethodName         = "/artist.ArtistService/IsFollowingArtist"
	ArtistService_CreateAuthoredTrackArtist_FullMethodName = "/artist.ArtistService/CreateAuthoredTrackArtist"
)

// ArtistServiceClient is the client API for ArtistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtistServiceClient interface {
	GetFollowedArtists(ctx context.Context, in *GetFollowedArtistsRequest, opts ...grpc.CallOption) (*GetFollowedArtistsResponse, error)
	GetArtistDetails(ctx context.Context, in *GetArtistDetailsRequest, opts ...grpc.CallOption) (*GetArtistDetailsResponse, error)
	SearchArtists(ctx context.Context, in *SearchArtistsRequest, opts ...grpc.CallOption) (*SearchArtistsResponse, error)
	FollowArtist(ctx context.Context, in *FollowArtistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IsFollowingArtist(ctx context.Context, in *IsFollowingArtistRequest, opts ...grpc.CallOption) (*IsFollowingArtistResponse, error)
	CreateAuthoredTrackArtist(ctx context.Context, in *CreateAuthoredTrackArtistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type artistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtistServiceClient(cc grpc.ClientConnInterface) ArtistServiceClient {
	return &artistServiceClient{cc}
}

func (c *artistServiceClient) GetFollowedArtists(ctx context.Context, in *GetFollowedArtistsRequest, opts ...grpc.CallOption) (*GetFollowedArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowedArtistsResponse)
	err := c.cc.Invoke(ctx, ArtistService_GetFollowedArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistServiceClient) GetArtistDetails(ctx context.Context, in *GetArtistDetailsRequest, opts ...grpc.CallOption) (*GetArtistDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtistDetailsResponse)
	err := c.cc.Invoke(ctx, ArtistService_GetArtistDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistServiceClient) SearchArtists(ctx context.Context, in *SearchArtistsRequest, opts ...grpc.CallOption) (*SearchArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArtistsResponse)
	err := c.cc.Invoke(ctx, ArtistService_SearchArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistServiceClient) FollowArtist(ctx context.Context, in *FollowArtistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ArtistService_FollowArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistServiceClient) IsFollowingArtist(ctx context.Context, in *IsFollowingArtistRequest, opts ...grpc.CallOption) (*IsFollowingArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowingArtistResponse)
	err := c.cc.Invoke(ctx, ArtistService_IsFollowingArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistServiceClient) CreateAuthoredTrackArtist(ctx context.Context, in *CreateAuthoredTrackArtistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ArtistService_CreateAuthoredTrackArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtistServiceServer is the server API for ArtistService service.
// All implementations must embed UnimplementedArtistServiceServer
// for forward compatibility.
type ArtistServiceServer interface {
	GetFollowedArtists(context.Context, *GetFollowedArtistsRequest) (*GetFollowedArtistsResponse, error)
	GetArtistDetails(context.Context, *GetArtistDetailsRequest) (*GetArtistDetailsResponse, error)
	SearchArtists(context.Context, *SearchArtistsRequest) (*SearchArtistsResponse, error)
	FollowArtist(context.Context, *FollowArtistRequest) (*emptypb.Empty, error)
	IsFollowingArtist(context.Context, *IsFollowingArtistRequest) (*IsFollowingArtistResponse, error)
	CreateAuthoredTrackArtist(context.Context, *CreateAuthoredTrackArtistRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedArtistServiceServer()
}

// UnimplementedArtistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtistServiceServer struct{}

func (UnimplementedArtistServiceServer) GetFollowedArtists(context.Context, *GetFollowedArtistsRequest) (*GetFollowedArtistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowedArtists not implemented")
}
func (UnimplementedArtistServiceServer) GetArtistDetails(context.Context, *GetArtistDetailsRequest) (*GetArtistDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtistDetails not implemented")
}
func (UnimplementedArtistServiceServer) SearchArtists(context.Context, *SearchArtistsRequest) (*SearchArtistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtists not implemented")
}
func (UnimplementedArtistServiceServer) FollowArtist(context.Context, *FollowArtistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowArtist not implemented")
}
func (UnimplementedArtistServiceServer) IsFollowingArtist(context.Context, *IsFollowingArtistRequest) (*IsFollowingArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFollowingArtist not implemented")
}
func (UnimplementedArtistServiceServer) CreateAuthoredTrackArtist(context.Context, *CreateAuthoredTrackArtistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthoredTrackArtist not implemented")
}
func (UnimplementedArtistServiceServer) mustEmbedUnimplementedArtistServiceServer() {}
func (UnimplementedArtistServiceServer) testEmbeddedByValue()                       {}

// UnsafeArtistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtistServiceServer will
// result in compilation errors.
type UnsafeArtistServiceServer interface {
	mustEmbedUnimplementedArtistServiceServer()
}

func RegisterArtistServiceServer(s grpc.ServiceRegistrar, srv ArtistServiceServer) {
	// If the following call panics, it indicates UnimplementedArtistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtistService_ServiceDesc, srv)
}

func _ArtistService_GetFollowedArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowedArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServiceServer).GetFollowedArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistService_GetFollowedArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServiceServer).GetFollowedArtists(ctx, req.(*GetFollowedArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtistService_GetArtistDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServiceServer).GetArtistDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistService_GetArtistDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServiceServer).GetArtistDetails(ctx, req.(*GetArtistDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtistService_SearchArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServiceServer).SearchArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistService_SearchArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServiceServer).SearchArtists(ctx, req.(*SearchArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtistService_FollowArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServiceServer).FollowArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistService_FollowArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServiceServer).FollowArtist(ctx, req.(*FollowArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtistService_IsFollowingArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowingArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServiceServer).IsFollowingArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistService_IsFollowingArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServiceServer).IsFollowingArtist(ctx, req.(*IsFollowingArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtistService_CreateAuthoredTrackArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthoredTrackArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServiceServer).CreateAuthoredTrackArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistService_CreateAuthoredTrackArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServiceServer).CreateAuthoredTrackArtist(ctx, req.(*CreateAuthoredTrackArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtistService_ServiceDesc is the grpc.ServiceDesc for ArtistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artist.ArtistService",
	HandlerType: (*ArtistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowedArtists",
			Handler:    _ArtistService_GetFollowedArtists_Handler,
		},
		{
			MethodName: "GetArtistDetails",
			Handler:    _ArtistService_GetArtistDetails_Handler,
		},
		{
			MethodName: "SearchArtists",
			Handler:    _ArtistService_SearchArtists_Handler,
		},
		{
			MethodName: "FollowArtist",
			Handler:    _ArtistService_FollowArtist_Handler,
		},
		{
			MethodName: "IsFollowingArtist",
			Handler:    _ArtistService_IsFollowingArtist_Handler,
		},
		{
			MethodName: "CreateAuthoredTrackArtist",
			Handler:    _ArtistService_CreateAuthoredTrackArtist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/artist.proto",
}
