// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> fetchHighestAudioStreamUrl({required String videoId}) => RustLib
    .instance
    .api
    .crateApiTydleCallerFetchHighestAudioStreamUrl(videoId: videoId);

Future<String> fetchHighestVideoStreamUrl({required String videoId}) => RustLib
    .instance
    .api
    .crateApiTydleCallerFetchHighestVideoStreamUrl(videoId: videoId);
