// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<Stream> fetchHighestAudioStream({required String videoId}) => RustLib
    .instance
    .api
    .crateApiTydleCallerFetchHighestAudioStream(videoId: videoId);

class Stream {
  final StreamMetadata metadata;
  final String url;

  const Stream({required this.metadata, required this.url});

  @override
  int get hashCode => metadata.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Stream &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          url == other.url;
}

class StreamMetadata {
  final double bitrate;
  final String ext;
  final String codec;
  final String videoId;
  final String source;

  const StreamMetadata({
    required this.bitrate,
    required this.ext,
    required this.codec,
    required this.videoId,
    required this.source,
  });

  @override
  int get hashCode =>
      bitrate.hashCode ^
      ext.hashCode ^
      codec.hashCode ^
      videoId.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamMetadata &&
          runtimeType == other.runtimeType &&
          bitrate == other.bitrate &&
          ext == other.ext &&
          codec == other.codec &&
          videoId == other.videoId &&
          source == other.source;
}
